### ISSUE TITLE
字节跳动

### ISSUE THREAD

**Issue by AlexanderMisel** [fcitx/fcitx5-chinese-addons#108]
![image](https://user-images.githubusercontent.com/7542439/196015968-6977b1c8-18fb-451a-82f2-fd2d0de15c7a.png)

字节跳动的“jie”被无故拆开，如果不是用云词库的话就会打不出这个词。

**Comment by wengxt** [comment]
没什么问题。词库里也没有字节跳动

ji e 可以被看作饥饿之类。就好像 xian 和  xi an 会同时参与组句。

![图片](https://user-images.githubusercontent.com/259684/196016172-26d2179c-c35c-44ec-8407-4bf93db56027.png)
你可以取消这个选项

**Comment by AlexanderMisel** [comment]
但是“zijie”应当识别成“字节”而不是“字饥饿”吧，这个可以智能识别吗？

**Comment by wengxt** [comment]
排序哪个靠前取决于模型当中字节 和 字饥饿分别计算得出的概率评分

**Comment by wengxt** [comment]
饥饿只是用来举例，实际在你输入的例子 「自己而跳动」 其实还是一个挺通顺的句子的，字节跳动作为近年的才变得比较知名「公司名字」，并不一定会出现在用于训练的数据当中。这只能说是预期中的一个现象了
