### ISSUE TITLE
建议主键盘和小键盘区的数字及符号区别分开

### ISSUE THREAD

**Issue by loongson444** [fcitx/fcitx5-chinese-addons#114]
我用三维天然码，编码为26个字母＋1－9数字，原来4.0的版本是可以区分主键盘的数字和小键盘的数字的，只有主键盘的数字可以作为编码，现在5.0的主键盘数字键不可以作为第二个编码了，小键盘的倒是可以。可以不可以改为主键盘的数字键可以作为全输入编码，小键盘的作为选字或者是纯数字输入？

**Comment by wengxt** [comment]
有没有码表配置能让我测试一下

**Comment by loongson444** [comment]
应该是我表述不清楚了。现在是主键盘第二个数字输入不了作为编码。
码表在这：
https://www.123pan.com/s/7V3uVv-FxRBH提取码:cZrr
