### ISSUE TITLE
建议主键盘和小键盘区的数字及符号区别分开

### ISSUE THREAD

**Issue by loongson444** [fcitx/fcitx5-chinese-addons#115]
https://github.com/fcitx/fcitx5-chinese-addons/issues/114

        有没有码表配置能让我测试一下

应该是我表述不清楚了。现在是主键盘第二个数字输入不了作为编码。
码表在这：
https://www.123pan.com/s/7V3uVv-FxRBH提取码:cZrr

**Comment by wengxt** [comment]
主键盘第二个数字什么意思

**Comment by wengxt** [comment]
我觉得你没有理解我之前的意思，另外你的码表配置本身还有问题，你用这个码表配置试试

```
[InputMethod]
Name[ca]=Trm
Name[da]=Trm
Name[de]=Trm
Name[ko]=Trm
Name[ru]=Пиньинь
Name[zh_CN]=天然码
Name=Trm GBK
Icon=fcitx-trm
Label=天
LangCode=zh_CN
Addon=table
Configurable=True

[Table]
File=table/trmgbk.dict
AutoSelect=True
AutoSelectLength=-1
NoMatchAutoSelectLength=-1
NoSortInputLength=2
Hint=True
MatchingKey=0
PinyinKey=@
OrderPolicy=Freq
UseFullWidth=True
QuickPhraseKey=semicolon
AutoPhraseLength=4
SaveAutoPhraseAfter=3
UseContextRelatedOrder=False

[Table/PrevPage]
0=Up
1=minus

[Table/NextPage]
0=Down
1=equal

[Table/Selection]
0=KP_0
1=KP_1
2=KP_2
3=KP_3
4=KP_4
5=KP_5
6=KP_6
7=KP_7
8=KP_8
9=KP_9
```

**Comment by wengxt** [comment]
这个配置可以正常用数字键作为编码输入，选词用小键盘

![image](https://user-images.githubusercontent.com/259684/207892739-06251c14-f80d-4f8d-99b1-fdaeee4bcdff.png)

**Comment by loongson444** [comment]
码表配置文件忘了抄哪的了，在4.0是正常的。
这么配置，主键盘数字是正常了，但小键盘也还是可以用作编码而不是仅仅选字，且如果设为从1开始，后面的候选字就没编号了，打完字不管是直接上屏的还是按空格上屏的，上完屏后都会有汉字输入候选框且乌汉字“的”开始。
o7d2的编码对应：汉字：别处 另外

**Comment by wengxt** [comment]
代码都是重新写的，不要太纠结以前什么样

建议描述清楚你的预期行为

这个天然码是有数字做码的，你预期的行为中应该怎么选词呢，还是根本不选词或者鼠标选词？

输入后有候选框是联想预测功能？那你得开启那个功能。

**Comment by loongson444** [comment]
我的预期是：主键盘全部数字作为编码，小键盘的选择上屏。

现在你给的配置文件，输入完后自动有个0的输入候选框出来而不是完全消失隐藏，且小键盘的数字依然是可以作为编码。

**Comment by wengxt** [comment]
第一个问题，你在托盘里点一下那个预测，把这个功能关闭即可。默认状态是不开的
第二个问题，得在代码里加一个判断
