### ISSUE TITLE
请问中文输入法有没有类似百度、搜狗这样的状态条功能？

### ISSUE THREAD

**Issue by rico256-cn** [fcitx/fcitx5-chinese-addons#116]
请问中文输入法有没有类似百度、搜狗下面这样的状态条功能？

<img width="164" alt="image" src="https://user-images.githubusercontent.com/60219649/208843301-e22d9b4f-fde2-4422-bfb7-78d2bdccafeb.png">

**Comment by rico256-cn** [comment]
<img width="164" alt="image" src="https://user-images.githubusercontent.com/60219649/208843359-73a8ee4d-7c4c-4989-9365-90538b9304c1.png">

**Comment by rocka** [comment]
fcitx5 没有状态条了

https://github.com/fcitx/fcitx5/issues/680

**Comment by wengxt** [comment]
没有。只有托盘图标。
