### ISSUE TITLE
5.0.15/16版本存在拼音输入乱码问题

### ISSUE THREAD

**Issue by rico256-cn** [fcitx/fcitx5-chinese-addons#117]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/60219649/209756578-5a9bd0e4-dd2f-497c-8a8b-78471d2fa0f3.png">

确认是5.0.15/16版本引入的，5.0.14都不存在这个问题。

之前提到下面了，重新提个 issue 吧
https://github.com/fcitx/fcitx5/issues/691

**Comment by wengxt** [comment]
我觉得是你用的库或者文件有问题。libime 的版本是什么，从哪里安装的，安装到哪了？

然后你这个排序的情况看起来也很可疑，建议先清除 ~/.local/share/fcitx5/pinyin 用全新用户再看看

**Comment by rico256-cn** [comment]
@wengxt  
编译过程和版本信息看这里。路径安装我现在 follow debian的系统规范，所以装上一把就 ok 的。

乱码的问题，除了截图以外，在选词的时候继续下翻页，会遇到更多（相比正常的版本多了很多），很明显选词出了问题。

建议先清除 ~/.local/share/fcitx5/pinyin 用全新用户再看看 ==》 不需要清理，我的排除方法很简单，我直接在下面这个编译的基础上 用<=5.0.14的fcitx5-chinese-addons版本(从5.0.4 也就是 debian仓库里面的正常版本开始到5.0.10  我逐个测试过来的）编译替换就恢复正常了。


版本信息：
drwxrwxr-x 12 root root 4096 12月 27 13:13 fcitx5-5.0.21
drwxrwxr-x 12 root root 4096 12月 27 13:25 fcitx5-chinese-addons-5.0.16
drwxrwxr-x 10 root root 4096 12月 27 13:14 fcitx5-gtk-5.0.21
drwxrwxr-x 9 root root 4096 12月 27 13:14 fcitx5-lua-5.0.10
drwxrwxr-x 11 root root 4096 12月 27 13:13 fcitx5-qt-5.0.16
drwxr-xr-x 3 root root 39 12月 27 13:16 kenlm-bcd4af619a2fa45f5876d8855f7876cc09f663af
drwxrwxr-x 8 root root 4096 12月 27 13:24 libime-1.0.16
drwxrwxr-x 8 root root 4096 12月 27 13:09 xcb-imdkit-1.0.4

主要的编译流程如下：

1）xcb-imdkit
cmake -DCMAKE_INSTALL_PREFIX=/usr .
make -j 5 && make install/strip

2）fcitx5
cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_WAYLAND=ON -DENABLE_EMOJI=OFF .
make -j 5
make install/strip

3）fcitx5-qt
cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_QT4=OFF .
make -j 5
make install/strip

4）fcitx5-gtk

cd fcitx5-gtk
cmake -DENABLE_GTK4_IM_MODULE=Off -DCMAKE_INSTALL_PREFIX=/usr .
make -j 5
make install/strip

5）fcitx5-lua (依赖 lua-dev)
cmake -DCMAKE_INSTALL_PREFIX=/usr .
make -j 5 && make install/strip

6）libime ，依赖kenlm 包 需要单独git clone 解压下去丢到 libime 的 kenlm 目录下
cmake -DCMAKE_INSTALL_PREFIX=/usr .
make -j 5
make install/strip

7)fcitx5-chinese-addon 依赖新版 libime，必须编译

cmake -DENABLE_OPENCC=Off -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_CLOUDPINYIN=Off -DENABLE_BROWSER=Off .
make -j 5 && make install

8)fcitx5-config-tool
cd fcitx5-config-tool
mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make && make install/strip

**Comment by rico256-cn** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/60219649/209759033-b8c87004-ea74-4511-85a7-63f0724deaea.png">


排序，我默认开了一些模糊音，可能有一定影响。但和乱码无关。

**Comment by wengxt** [comment]
我已经说了，不能重现你的问题。

https://user-images.githubusercontent.com/259684/209850816-d0cc9579-6b63-424f-afa4-618528e881e8.mp4

所以我才要搞清楚你的环境里有什么问题

我认为你有什么文件损坏了。

另外，作为一个好习惯，不要用 root 编译。

**Comment by kingysu** [comment]
> <img alt="image" width="653" src="https://user-images.githubusercontent.com/60219649/209756578-5a9bd0e4-dd2f-497c-8a8b-78471d2fa0f3.png">
> 
> 确认是5.0.15/16版本引入的，5.0.14都不存在这个问题。
> 
> 之前提到下面了，重新提个 issue 吧 [fcitx/fcitx5#691](https://github.com/fcitx/fcitx5/issues/691)

从你给的截图来看，可以推断出两个结论：

1. 你可能使用了GTK框架用来实现输入窗口
2. 候选结果中的2选对应的所谓乱码其实应该是候选：“**𧢹**”。这个字应该是个生僻字。你的计算机安装的字体应该是不支持这个字的。

建议：
1. 安装font-manager，该软件可以预览文字的显示效果以及是否得到支持
2. 通过通过[网址](https://name.vurls.cn/ui/index/uchar/ )：查询编码所对应的文字

**Comment by wengxt** [comment]
@kingysu 我看他文本输出是乱码以为确实打了乱码 ´_>` ……原来是正经的字吗

也许他终端编码还有其他问题吧所以more看起来不对，或者你终端对unicode支持不够好…

**Comment by wengxt** [comment]
fcitx 拼音能支持输入的字远比你想象的多，拼音里有一个设置可以关掉很多生僻字你可以看看

**Comment by wengxt** [comment]
另外你所谓的版本问题，因为 libime 在新版本拆分了字库到两个词库，sc.dict 的字减少了，而 5.0.14 只支持这一个老文件名，所以你没看到这个字。同期发布的 5.0.15 是支持读取两个词库，所以你才看到了这个字。

字库也并没有在最近版本添加，如果每次都用同时期的最新 libime 是看不到任何区别的。

**Comment by rico256-cn** [comment]
@kingysu   根据你的提示，我安装了 font-noto 全套字体，测试机器上依旧是显示方块。。。
$dpkg -l | grep noto
ii  fonts-noto                                     20201225-1                      all          metapackage to pull in all Noto fonts
ii  fonts-noto-cjk                                 1:20201206-cjk+repack1-1        all          "No Tofu" font families with large Unicode coverage (CJK regular and bold)
ii  fonts-noto-cjk-extra                           1:20201206-cjk+repack1-1        all          "No Tofu" font families with large Unicode coverage (CJK all weight)
ii  fonts-noto-color-emoji                         0~20200916-1                    all          color emoji font from Google
ii  fonts-noto-core                                20201225-1                      all          "No Tofu" font families with large Unicode coverage (core)
ii  fonts-noto-extra                               20201225-1                      all          "No Tofu" font families with large Unicode coverage (extra)
ii  fonts-noto-mono                                20201225-1                      all          "No Tofu" monospaced font family with large Unicode coverage
ii  fonts-noto-ui-core                             20201225-1                      all          "No Tofu" font families with large Unicode coverage (UI core)
ii  fonts-noto-ui-extra                            20201225-1                      all          "No Tofu" font families with large Unicode coverage (UI extra)
ii  fonts-noto-unhinted                            20201225-1                      all          "No Tofu" font families with large Unicode coverage (unhinted)



@wengxt  

fcitx 拼音能支持输入的字远比你想象的多，拼音里有一个设置可以关掉很多生僻字你可以看看

===》 具体是那个设置项？ 我在GUI 里面没有看到 有 生辟字 选项啊。

另外你所谓的版本问题，因为 libime 在新版本拆分了字库到两个词库
==》  是extb.dict 吧？  我在裁剪的系统上，根据 inputmethod 里面的配置信息，确实同步清理了拼音和五笔之外的输入法字典。 不清楚这 ok不？但我在我测试机上，下面目录的文件都是libime-1.0.16里面编译完整安装的，我确实也可以发现5.0.14 没有乱码，5.0.15/16会出现乱码。请问这个新拆分的字库是生僻字还是什么？

$ls -al  /usr/share/libime

-rw-r--r--   1 root root  343917 12月 26 14:11 extb.dict
-rw-r--r--   1 root root 6046254 12月 26 14:11 sc.dict
-rw-r--r--   1 root root 4016553 12月 26 14:12 wbx.main.dict

**Comment by kingysu** [comment]
> 



> @kingysu 根据你的提示，我安装了 font-noto 全套字体，测试机器上依旧是显示方块。。。 $dpkg -l | grep noto ii fonts-noto 20201225-1 all metapackage to pull in all Noto fonts ii fonts-noto-cjk 1:20201206-cjk+repack1-1 all "No Tofu" font families with large Unicode coverage (CJK regular and bold) ii fonts-noto-cjk-extra 1:20201206-cjk+repack1-1 all "No Tofu" font families with large Unicode coverage (CJK all weight) ii fonts-noto-color-emoji 0~20200916-1 all color emoji font from Google ii fonts-noto-core 20201225-1 all "No Tofu" font families with large Unicode coverage (core) ii fonts-noto-extra 20201225-1 all "No Tofu" font families with large Unicode coverage (extra) ii fonts-noto-mono 20201225-1 all "No Tofu" monospaced font family with large Unicode coverage ii fonts-noto-ui-core 20201225-1 all "No Tofu" font families with large Unicode coverage (UI core) ii fonts-noto-ui-extra 20201225-1 all "No Tofu" font families with large Unicode coverage (UI extra) ii fonts-noto-unhinted 20201225-1 all "No Tofu" font families with large Unicode coverage (unhinted)
> 
> @wengxt
> 
> fcitx 拼音能支持输入的字远比你想象的多，拼音里有一个设置可以关掉很多生僻字你可以看看
> 
> ===》 具体是那个设置项？ 我在GUI 里面没有看到 有 生辟字 选项啊。
> 
> 另外你所谓的版本问题，因为 libime 在新版本拆分了字库到两个词库 ==》 是extb.dict 吧？ 我在裁剪的系统上，根据 inputmethod 里面的配置信息，确实同步清理了拼音和五笔之外的输入法字典。 不清楚这 ok不？但我在我测试机上，下面目录的文件都是libime-1.0.16里面编译完整安装的，我确实也可以发现5.0.14 没有乱码，5.0.15/16会出现乱码。请问这个新拆分的字库是生僻字还是什么？
> 
> $ls -al /usr/share/libime
> 
> -rw-r--r-- 1 root root 343917 12月 26 14:11 extb.dict -rw-r--r-- 1 root root 6046254 12月 26 14:11 sc.dict -rw-r--r-- 1 root root 4016553 12月 26 14:12 wbx.main.dict

很不幸的是，Noto字体不支持：“**𧢹**”。Noto Sans CJK支持的中文字符数量应该是2万多个。

**Comment by wengxt** [comment]
> @kingysu 根据你的提示，我安装了 font-noto 全套字体，测试机器上依旧是显示方块。。。 $dpkg -l | grep noto ii fonts-noto 20201225-1 all metapackage to pull in all Noto fonts ii fonts-noto-cjk 1:20201206-cjk+repack1-1 all "No Tofu" font families with large Unicode coverage (CJK regular and bold) ii fonts-noto-cjk-extra 1:20201206-cjk+repack1-1 all "No Tofu" font families with large Unicode coverage (CJK all weight) ii fonts-noto-color-emoji 0~20200916-1 all color emoji font from Google ii fonts-noto-core 20201225-1 all "No Tofu" font families with large Unicode coverage (core) ii fonts-noto-extra 20201225-1 all "No Tofu" font families with large Unicode coverage (extra) ii fonts-noto-mono 20201225-1 all "No Tofu" monospaced font family with large Unicode coverage ii fonts-noto-ui-core 20201225-1 all "No Tofu" font families with large Unicode coverage (UI core) ii fonts-noto-ui-extra 20201225-1 all "No Tofu" font families with large Unicode coverage (UI extra) ii fonts-noto-unhinted 20201225-1 all "No Tofu" font families with large Unicode coverage (unhinted)
> 
> @wengxt
> 
> fcitx 拼音能支持输入的字远比你想象的多，拼音里有一个设置可以关掉很多生僻字你可以看看
> 
> ===》 具体是那个设置项？ 我在GUI 里面没有看到 有 生辟字 选项啊。
> 
> 另外你所谓的版本问题，因为 libime 在新版本拆分了字库到两个词库 ==》 是extb.dict 吧？ 我在裁剪的系统上，根据 inputmethod 里面的配置信息，确实同步清理了拼音和五笔之外的输入法字典。 不清楚这 ok不？但我在我测试机上，下面目录的文件都是libime-1.0.16里面编译完整安装的，我确实也可以发现5.0.14 没有乱码，5.0.15/16会出现乱码。请问这个新拆分的字库是生僻字还是什么？
> 
> $ls -al /usr/share/libime
> 
> -rw-r--r-- 1 root root 343917 12月 26 14:11 extb.dict -rw-r--r-- 1 root root 6046254 12月 26 14:11 sc.dict -rw-r--r-- 1 root root 4016553 12月 26 14:12 wbx.main.dict

我的意思是，如果你用和 chinese-addons 5.0.14 同时期发布的 libime 1.0.13 ，就会得到和 fcitx5-chinese-addons 5.0.16 + libime 1.0.16 相同的结果。

1.0.16 的 sc.dict  + extb.dict  = 1.0.13 的  sc.dict

而 5.0.14 只知道加载sc.dict 一个文件，所以你把他和  1.0.16 libime 一起用自然会得到字变少了的结果。

不想看见生僻字去 5.0.16 的拼音配置里关掉即可。

**Comment by rico256-cn** [comment]
@wengxt  非常感谢，  不过在拼音配置里面 不是叫生辟字，是 UNICODE-CJK 拓展区B， 关掉这个，确实没有看到 NOTO方块了。 UI 界面上 可以改成生僻字 可能直观点。。。  

<img width="695" alt="image" src="https://user-images.githubusercontent.com/60219649/209898390-fcf8994a-94a9-48c7-942b-9ed87cce0c91.png">

**Comment by rico256-cn** [comment]
另外，我也测试过 debian 11 仓库里面的 fcitx5全套啊， 这个好像默认是不带生辟字显示配置的，因为我确实也发现仓库里面装的打字是正常的。

**Comment by wengxt** [comment]
@rico256-cn debian 仓库的问题是太老 1.0.5 的时候更新了一大批字库和读音。

**Comment by rico256-cn** [comment]
唉，没办法，我比较笨，只能人肉测试的过程中长见识了。。。

**Comment by rico256-cn** [comment]
@wengxt   正常 linux 系统上装中文字体（noto 也算是主流了吧），如果遇到上面说的新版本更新字库+缺省 unicode扩展 b 字符开启，应该都会遇到我说的问题。 建议后续这个地方配置项缺省关闭 + 特殊提示备注下？
