### ISSUE TITLE
[feature request]Want search unicode to appear when entering a final (u, i, v) that should not appear at the beginning (instead of the default, press Ctrl + Alt + Shift + U)

### ISSUE THREAD

**Issue by tjw123hh** [fcitx/fcitx5-chinese-addons#118]
I want search unicode to appear when entering a final (u, i, v) that should not appear at the beginning because search unicode's keyboard shortcuts can be easily clashing (the default Ctrl + Alt + Shift + U is tricky, because who wants to press four keys at once?

**Comment by wengxt** [comment]
I don't know if make two more additional keys while we already have V worth it. Keep it as is allows some other function to work, for example, the English word.

The semicolon one is fcitx's own historical option.

Unicode itself is a rarely used functionality for most people. I don't really want to make u to enter unicode mode, not to mention that it has different selection key to allow digit to be typed in unicode mode which means a different set of keys. Ctrl+Alt+Shift+U is intended to not conflicts with Gtk's built-in unicode mode, but now a separate Gtk-like unicode mode is implemented with Ctrl+Shift+U in fcitx. Also, all these keys are customizable, you can change to a simpler one.

Instead, I may rather consider make U enter a standalone stroke mode (we already have stroke mode, but it's mixed and may not show all character that matches the stroke). https://pinyin.sogou.com/help.php?list=3&q=8

**Comment by tjw123hh** [comment]
But without searching unicode, I can't even enter special symbols such as serial numbers

**Comment by wengxt** [comment]
You can customize quick phrase to allow you type anything you want.

Also, if you have fcitx5-lua installed, quick phrase can be extended with lua and there's already built in symbol table when using pinyin (type fh which stands for 符号)
