### ISSUE TITLE
希望能加入更便捷的分词功能

### ISSUE THREAD

**Issue by Astro-Aionia** [fcitx/fcitx5-chinese-addons#124]
在安卓的fcitx输入法上, 输入`xian`和`xi'an`这一类场景, 目前是通过长按屏幕键盘<kbd>z</kbd>键插入分词符<kbd>'</kbd>, 如果能像安卓主流输入法一样添加一个专门的分词按键将会方便很多.

**Comment by wengxt** [comment]
首先，有内模糊切分，其次，应当报给安卓
