### ISSUE TITLE
能否让两字词语排在单字前面？

### ISSUE THREAD

**Issue by yilksd** [fcitx/fcitx5-chinese-addons#128]
一般输入法都是字数多的候选词排在前面，但是fcitx5-chinese-addons却没有这个规律，比如输入“weixin”甚至“微信”这个词语排在好几页之后，很多单字都在它前面。
[录屏 2023年04月03日 18时37分56秒.webm](https://user-images.githubusercontent.com/7428046/229486782-984eee66-2bf3-4b5a-be7a-99dc7ee7c3b2.webm)
我清空了自定义词典后测试也还是如此。

**Comment by wengxt** [comment]
不能，计算的是综合评分。问题是模型没有对应的词
