### ISSUE TITLE
笔画以外的辅助码过滤

### ISSUE THREAD

**Issue by wengxt** [fcitx/fcitx5-chinese-addons#130]
考虑支持小鹤或者自然码的辅助码进行过滤

**Comment by deonblue** [comment]
非常需要这个功能

**Comment by wengxt** [comment]
目前来看你直接挂接 https://github.com/fanqi/sogou-flypy/blob/master/sogou-flypy.txt 给 customphrase 即可 

具体辅助码过滤特别是词的形式其实并不太明确

如果有别的输入法已经实现的模式再考虑
