### ISSUE TITLE
我掛形碼打繁體，反查的拼音喜歡用小鶴雙拼打繁體，能加個導入自定義反查方案的功能嗎？

### ISSUE THREAD

**Issue by xuma-input** [fcitx/fcitx5-chinese-addons#132]
我掛形碼打繁體，反查的拼音喜歡用小鶴雙拼打繁體，能加個**導入自定義反查方案**的功能嗎？

**Comment by wengxt** [comment]
能解释一下需求吗？

是指想要反查的时候显示小鹤对应的按键？

**Comment by xuma-input** [comment]
> 能理解一下需要吗？
> 
> 是指要反查的时候显示小鹤对应的按键吗？

比如我用「五筆」，按z鍵時會觸發自定義反查方案，顯示五筆對應的單字或詞組的編碼。

**Comment by wengxt** [comment]
反查当前码表的码是内置的功能，其实是和添加删除做到一起的，按 ctrl + 8 或者选中

反查拼音是单独的查拼音功能，如果你对反查拼音本身有自定义要求那是另一个问题

**Comment by xuma-input** [comment]
> 对反查拼音本身有自定义要求

對反查拼音本身有自定義要求
