### ISSUE TITLE
Conflict in Fedora 38

### ISSUE THREAD

**Issue by pvcgary** [fcitx/fcitx5-chinese-addons#136]
After install, error message:
内部错误：Error running transaction: file /usr/share/icons/hicolor/16x16/apps/fcitx-fullwidth-active.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/16x16/apps/fcitx-fullwidth-inactive.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/16x16/apps/fcitx-punc-active.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/16x16/apps/fcitx-punc-inactive.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/22x22/apps/fcitx-fullwidth-active.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/22x22/apps/fcitx-fullwidth-inactive.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/22x22/apps/fcitx-punc-active.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/22x22/apps/fcitx-punc-inactive.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/24x24/apps/fcitx-fullwidth-active.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/24x24/apps/fcitx-fullwidth-inactive.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/24x24/apps/fcitx-punc-active.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch
file /usr/share/icons/hicolor/24x24/apps/fcitx-punc-inactive.png from install of fcitx5-chinese-addons-data-5.0.17-1.fc38.noarch conflicts with file from package fcitx-data-4.2.9.9-3.fc38.noarch

**Comment by wengxt** [comment]
just uninstall fcitx4.

**Comment by pvcgary** [comment]
> just uninstall fcitx4.

It is working now, tks.

**Comment by pvcgary** [comment]
another error message after restart
imsettings-daemon
Unable to keep Input Method running
Giving up to bring the process up because main Input Method process for fcitx5 rapidly died many times. See $XDG_CACHE_HOME/imsettings.log for more details.

**Comment by pvcgary** [comment]
> 

But cannot find $XDG_CACHE_HOME/imsettings/log

**Comment by karuboniru** [comment]
remove `fcitx5-autostart` if you are using imsettings

**Comment by pvcgary** [comment]
> remove `fcitx5-autostart` if you are using imsettings

tks
removed but error message persist

**Comment by wengxt** [comment]
@pvcgary please check how you auto start fcitx, if you do that on your own, or you didnt configure imsettings to use fcitx5, you can go to im-chooser to disable it or just remove imsettings.

**Comment by pvcgary** [comment]
> @pvcgary please check how you auto start fcitx, if you do that on your own, or you didnt configure imsettings to use fcitx5, you can go to im-chooser to disable it or just remove imsettings.

tks @wengxt after remove im-chooser everything fine now
