### ISSUE TITLE
Pinyin preedit changes the font in Libreoffice

### ISSUE THREAD

**Issue by ewtoombs** [fcitx/fcitx5-chinese-addons#139]
## To reproduce
0. Make sure "show preedit in application" is on in fcitx5-configtool.
1. Open libreoffice.
2. Change to a Chinese font other than the system default.
3. Type something in pinyin.

### Expected results
The non-default Chinese font should remain.

### Actual results
The font changes to the system default. Sometimes, it changes to specifically Times New Roman.

## Extra
This may be due to libreoffice, but I don't think so. Because of the workaround. Here are the versions used:
```
Name            : fcitx5
Version         : 5.0.23-2
Name            : fcitx5-gtk
Version         : 5.0.23-1
Name            : fcitx5-chinese-addons
Version         : 5.0.17-1
Name            : libreoffice-still
Version         : 7.4.7-4
Name            : sway
Version         : 1:1.8.1-1
Name            : gtk3
Version         : 1:3.24.38-1
```

### Workaround
Disable "show preedit in application" in fcitx5-configtool.

**Comment by wengxt** [comment]
@ewtoombs please report to libreoffice.
