### ISSUE TITLE
custom punc.mb.zh_CN content

### ISSUE THREAD

**Issue by jeffrey4l** [fcitx/fcitx5-chinese-addons#147]
如果可以自定义 `punc.mb.zh_CN` 的内容

我不太想用那些中文字符。一般只想用英文的。我都是直接改写了 `/usr/share/fcitx5/punctuation/punc.mb.zh_CN` 这个文件内容。但是每次升级都会被还原。有没有在 home 目录改写的方式？

**Comment by rocka** [comment]
`~/.local/share/fcitx5/punctuation/punc.mb.zh_CN`

或者用 fcitx5-configtool ，直接在 附加组件 - 拼音 - 标点 里面编辑。
