### ISSUE TITLE
[建议] 云拼音在获取到和已显示候选词相同结果时仍然占据第二候选词栏位

### ISSUE THREAD

**Issue by escape0707** [fcitx/fcitx5-chinese-addons#148]
由于不是 bug 而是特性讨论，不太适用报 bug 模板，便简要描述如下：
在启用云拼音后，云拼音的候选词在获取结果的过程中占据第二号候选词位置的。但是如果获取的结果和已经显示的其他候选词重复的时候它就会直接消失，这时后面的关键词们就会往前移一位。这导致如果有时候网络较慢，已经准备手动选择三、四号词，结果云拼音位置突然消失则就会选错。降低输入效率。

可否参考其他有云拼音的输入法（比如 Windowns 10/11 上的微软拼音），即使云拼音获得了与已显示的其他候选词相同的结果，也保留其云朵的 emoji 在第二位，稳定其他候选词的位置呢？

**Comment by oldherl** [comment]
其实你可以用竖向的候选词框，这样就是每个词一行，位置比较固定了

**Comment by escape0707** [comment]
> 其实你可以用竖向的候选词框，这样就是每个词一行，位置比较固定了

是个比较有意思的方法，不过在打字的时候上下还是会跳动。另外竖向候选词在输入光标位于屏幕下缘的时候会在输入位置上方，第一候选词和拼音就离的太远了些。
