### ISSUE TITLE
关于常见模糊音的建议

### ISSUE THREAD

**Issue by cangkuai** [fcitx/fcitx5-chinese-addons#149]
建议添加一个修正常见输入错误的功能比如以下情况
zh打成hz
ch打成hc
sh打成hs
ing打成nig或者ign
ang打成nag或者agn

**Comment by oldherl** [comment]
……要不你学学双拼？

**Comment by cangkuai** [comment]
这些是我这几天用的时候总结出来的我容易打错的情况，不代表所有人都会容易出现这种错误

**Comment by rocka** [comment]
TL;DR: 已经有了

https://github.com/fcitx/libime/commit/9b63022f5fe630d4c6e8567e6cdc9568035fcbb9
https://github.com/fcitx/fcitx5-chinese-addons/commit/78bbde93d6b8d9fed8afc065950c8dba73c838fd
