### ISSUE TITLE
繁简切换消息超时默认值

### ISSUE THREAD

**Issue by c31io** [fcitx/fcitx5-chinese-addons#153]
https://github.com/fcitx/fcitx5/issues/884

每次切换都要点一下，繁简切换时人在电脑前，消息应默认短时间后消失。

**Comment by rocka** [comment]
你用的什么桌面环境？在 KDE 中，通知显示时间是可以设置的，默认情况下会在 5 秒种后自动消失

![image](https://github.com/fcitx/fcitx5-chinese-addons/assets/13914967/6be4914a-77f6-48b1-869b-ed813d44f7a2)

**Comment by c31io** [comment]
通知用[emersion/mako](https://github.com/emersion/mako)，默认长时间显示

不希望改变默认行为，会漏消息

**Comment by rocka** [comment]
看了一下它是有 `default-timeout` 选项的，你设置成 0 了？

https://github.com/emersion/mako/blob/b8a82cef0d15d2a88f2ba55e85dff7b6bd9a4060/mako.5.scd?plain=1#L250

```scd
*default-timeout*=_timeout_
	Set the default timeout to _timeout_ in milliseconds. To disable the
	timeout, set it to zero.

	Default: 0
```

担心漏消息的话不是应该设置一下保留历史之类的吗 ...
