### ISSUE TITLE
繁体模式候选词列表中显示了简体模式中的繁体字

### ISSUE THREAD

**Issue by wanzh5** [fcitx/fcitx5-chinese-addons#161]
简体模式的候选词列表中会有一些繁体字，切换成繁体模式后它们没有消失。最终这些字会显示两次。
建议把它们去掉或是转换成简体字。
例（截图）：
简体
![Screenshot_20240318_173905](https://github.com/fcitx/fcitx5-chinese-addons/assets/106989902/f74a271f-3e6e-4397-83d4-106395617495)
繁体
![Screenshot_20240318_173915](https://github.com/fcitx/fcitx5-chinese-addons/assets/106989902/0f527c9d-ab90-48e9-9617-153f89cc64e2)

**Comment by wengxt** [comment]
won't fix.
