### ISSUE TITLE
输入d开头的字母有时需要输入两次

### ISSUE THREAD

**Issue by cathaysia** [fcitx/fcitx5-chinese-addons#17]
问题描述

在calibre -> 编辑元数据 -> 逐个编辑元数据 -> 出版商。 这个标签，如果光标在标签开头输入 "电" 时，d需要打两次。但是如果光标前面已经有文字则不需要打两次

该问题只出现在“拼音”输入法中，rime没有这种情况

系统信息： archlinux, calibre 4.15.0-2 , fcitx5 0.0.0.20200509-3, fcitx5-chinese-addons 0.0.0.20200509-2

**Comment by wengxt** [comment]
表现上来说听起来是 calibre 的 bug，焦点没有切换过去之类的，只是 rime 意外不知处于什么原因没能触发？我没能重现。

建议录制视频看一下

**Comment by cathaysia** [comment]
这个问题可能确实是由于焦点的问题，我刚刚又试了几次，只有一次复现了这个问题。大概是calibre的问题
