### ISSUE TITLE
无法切换简体繁体

### ISSUE THREAD

**Issue by u5n** [fcitx/fcitx5-chinese-addons#170]
## Version

Ubuntu 24.04
fcitx5 5.1.7
Windowing System Wayland
fcitx5-chinese-addons 5.1.3-1build3

## Description
无法切换简体繁体，按快捷键无反应
尝试重新通过apt安装，没有效果
pinyin插件中"Simplified and Traditional Chinese Translation"选项点击后无任何内容
`fcitx5-configtool`报错`fcitx5-config: QDBusError("org.freedesktop.DBus.Error.InvalidArgs", "Addon does not exist.")`
该错误在系统升级到Ubuntu 24.04后出现，之前能正常使用

**Comment by wengxt** [comment]
fcitx5-diagnose 看看，不知道为什么 chttrans 没法加载，多半是打包/安装问题

**Comment by u5n** [comment]
> fcitx5-diagnose 看看，不知道为什么 chttrans 没法加载，多半是打包/安装问题

因为提示含敏感信息，我已将内容发送到您的谷歌邮箱中，请查收

**Comment by wengxt** [comment]
@u5n 看起来没装啊？装 fcitx5-module-chttrans  看看
