### ISSUE TITLE
[Feature Request] 希望拼音输入法添加输入特殊符号的功能

### ISSUE THREAD

**Issue by cathaysia** [fcitx/fcitx5-chinese-addons#18]
今天我输入特殊符号的时候发现用拼音输入法没法打出来序号，比如①，而且compose键也没有这个序列。

我现在有两种办法：

- 百度查出来这个符号
- 自己补充compose的功能

但是这样太麻烦了，希望您能考虑拼音输入法考虑添加输入特殊符号的功能。

**Comment by Aloxaf** [comment]
你可以自己往快速输入里面添加这个符号

**Comment by OliverLew** [comment]
我自己一直用的临时方案，比较方便，但需要一点英语能力：

1. Ctrl+Shift+Alt+U打开Unicode输入
2. 输入描述性的词，这个不一定提前知道，可能要试。比如你的例子就是`circle one`就能找到了

![fcitx-unidode](https://user-images.githubusercontent.com/12032219/85247650-08d24400-b481-11ea-82c7-d1103aeb2667.png)

**Comment by cathaysia** [comment]
> 我自己一直用的临时方案，比较方便，但需要一点英语能力：
> 
>     1. Ctrl+Shift+Alt+U打开Unicode输入
> 
>     2. 输入描述性的词，这个不一定提前知道，可能要试。比如你的例子就是`circle one`就能找到了
> 
>     3. Alt+N选择
> 
> 
> （我用的fcitx4，但应该5也是一样的）
> 
> ![fcitx-unidode](https://user-images.githubusercontent.com/12032219/85247650-08d24400-b481-11ea-82c7-d1103aeb2667.png)

Fcitx5 确实可以使用这个功能，谢谢

**Comment by cathaysia** [comment]
对于简单的字符，可以尝试拓展 Compose 键的功能。比如我的：

```shell
# ~/.XCompose
include "%L"

<Multi_key> <o> <1>     : "①" U2460
<Multi_key> <o> <2>     : "②" U2461
<Multi_key> <o> <3>     : "③" U2462
<Multi_key> <o> <4>     : "④" U2463
<Multi_key> <o> <5>     : "⑤" U2464
<Multi_key> <o> <6>     : "⑥" U2465
<Multi_key> <o> <7>     : "⑦" U2466
<Multi_key> <o> <8>     : "⑧" U2467
<Multi_key> <o> <9>     : "⑨" U2468
<Multi_key> <0> <1> <o> : "⑩" U2469
<Multi_key> <1> <1> <o> : "⑪" U246A
<Multi_key> <2> <1> <o> : "⑫" U246B
<Multi_key> <3> <1> <o> : "⑬" U246C
<Multi_key> <4> <1> <o> : "⑭" U246D
<Multi_key> <g> <a>     : "α"
<Multi_key> <g> <b>     : "β"
<Multi_key> <g> <g>     : "γ"

# 其他符号
<Multi_key> <.> <1>     : "·" U00B7 # 着重号
```

**Comment by wengxt** [comment]
这个功能基本上来说是交给 quickphrase 解决的。有自己的要求的话可以加入自己的 quickphrase 配置

不过考虑到 fcitx4 里有 pysym.mb 直接输入这个符号…可能加入一个 lua 脚本给 quickphrase 比较合适

**Comment by wengxt** [comment]
https://github.com/fcitx/fcitx5-chinese-addons/commit/61fe245936364a77b95f228114f0fbb2cd0b82f2
