### ISSUE TITLE
对非定码长的方案空码时自动上屏优化

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx/fcitx5-chinese-addons#182]
### 摘要 / Summary

我使用是中码五笔方案，这个方案单字码长与词组码并不定长。也就是与王码五笔的最长4码定长不同。在开启方案设置中的`自动选择候选词`将`没有匹配时自动选择`也开启后。自动选择的总不是全码的词，而是当前分段匹配到的词+新入输的空码字符，而不是像Rime中自动选择的全码词。

目前空码行为，大该有几种：`空码清屏`，`空码上屏英文编码`，`空码上屏全码匹配到词`+剩余分段，`空码上屏全码匹配到词`+剩余分段。fcitx5采用了最后一种。
### 替代方案 / Alternative Solution

挂在内置Rime插件中可以上正常选择上屏完整匹配的词

### 附加信息 / Additional Context

![Screenshot_20240518_142019_Fcitx5 for Android](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/c2f08639-15a3-4f6b-a03c-3cca26833cfb)
![Screenshot_20240518_142031_Fcitx5 for Android](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/920e191a-3022-4c70-b119-3bcca431eb36)

### 系统版本 / OS Version

Android13操作系统

### 应用版本 / App Version

0.0.9

### 插件版本 / Plugins Version

0.0.9

**Comment by wengxt** [comment]
@JUST-INTJ 请具体描述一下你输入了什么和想要的行为

**Comment by JUST-INTJ** [comment]
好的：比如词库中有：wqvb 你好、wqvbkb你好啊、kwkkwk 哈哈。我想打出：你好哈哈。输入wqvbkwkkwk 自动上屏会选择：`你好啊` +余下的码，我想选择的是 `你好` +余下的码。
![Screenshot_20240629_213945_Via](https://github.com/fcitx/fcitx5-chinese-addons/assets/43703941/231a6537-9014-4be6-9f27-965af1b6b98b)

**Comment by JUST-INTJ** [comment]
自动选择会选择到不完整编码的词， `哈哈` 编码就会被截断，变成命中其他字。

https://github.com/fcitx/fcitx5-chinese-addons/assets/43703941/bf8c2c63-7195-4bd8-b178-01b60afcfdcd

**Comment by JUST-INTJ** [comment]
内置的rime插件是正常的。

https://github.com/fcitx/fcitx5-chinese-addons/assets/43703941/0677d931-7dc5-4ac3-8471-b95d1360f153

**Comment by wengxt** [comment]
就是这么设计的
它保证的是自动选择发生的时候选的东西一定是你正在看到的
它不会回溯到某个之前的状态再去选择最佳的
rime支持你的需求你用rime就好了
