### ISSUE TITLE
单双书名号交替输入

### ISSUE THREAD

**Issue by tjw123hh** [fcitx/fcitx5-chinese-addons#186]
单双书名号应该交替使用（尽管不常用），但这目前无法通过修改配置文件实现
只能说是键盘排布太奇怪了（毕竟英文没有书名号这东西）：引号单双分开，前后不分；书名号前后分开，单双不分

目前想到的解决方式是与引号交替输入相同，但前书名号与后书名号的状态应该统一
即：
输入前书名号**之前**，状态改变
输入后书名号**之后**，状态改变
（之前之后可以对调，但两者不能相同）
这样甚至可以处理一个双书名号里面多个单书名号的情况

**Comment by wengxt** [comment]
标点配置里把书名号按键配置成像引号那样就行了
例如<配置成双书名号交替，>配置成单书名号交替
