### ISSUE TITLE
Compiling entire fcitx5 package, including fcitx5-chinese addons

### ISSUE THREAD

**Issue by hg2581** [fcitx/fcitx5-chinese-addons#187]
Doing the above on Rocky Linux 9. The compilation of chinese-addons fails with:

  Could not find a package configuration file provided by
  "Fcitx5Qt6WidgetsAddons" with any of the following names:

    Fcitx5Qt6WidgetsAddonsConfig.cmake
    fcitx5qt6widgetsaddons-config.cmake

Not sure which libraries might be missing? Should they already have been created by compiling fcitx5 itself or some other package needed? All other packages compile with the exception of fcitx5-config-qt which I have not yet found the reason why it does not get created although fcitx5-configure does...

Thanks in advance.

**Comment by wengxt** [comment]
@hg2581 It's asking for fcitx5-qt. You can disable it with some cmake option
