### ISSUE TITLE
SC-TC-JP Kanji converter does not list all possible results

### ISSUE THREAD

**Issue by MajoranaOedipus** [fcitx/fcitx5-chinese-addons#191]
## The description of the issue
The fcitx5-chinese-addons provides SC-TC-JP Kanji convert, both via native engine or [OpenCC](https://github.com/BYVoid/OpenCC/tree/master). 

Yet, when encountering situations like `台 -> 台臺` or `为 -> 為爲` (*Variants*), `历 -> 歷曆` or `干 -> 幹乾干` (*multiple traditional Kanjis simplified to one*), only one possible result is shown in the list for selection.

(Also in the `为` case, two identical `為` or `爲`, depending on the config, is shown, see figure below.

![two identical `爲`](https://github.com/user-attachments/assets/815fc4c5-bb98-4afe-af1a-45286fea286d)

## Possible solutions

- I will expect that for *single* Kanji cases, the addon should list all possible convertion result for user to select, and
- For multiple Kanji cases (i.e. in words or sentences), native or OpenCC convert API is good enough.

C.f https://github.com/BYVoid/OpenCC/issues/427#issuecomment-645443036, OpenCC seems to have `OpenCC::DictEntry` to list all possible results.

Since the OpenCC does not have a comprehensive API documents that I can find, I am not sure how to implement this.
(I am not familier with C++, and it seems that the API exposed for Python does not support all the functions.)

**Comment by wengxt** [comment]
the current of chttrans limitation can only do this
