### ISSUE TITLE
How do I set up Cangjie on my Android phone?

### ISSUE THREAD

**Issue by awlandy** [fcitx/fcitx5-chinese-addons#199]
I don't see the Cangjie option.
![noCangjie](https://github.com/user-attachments/assets/d6df335e-7f8c-4479-beaf-56093385c0ef)
Should Android users follow this guide?
https://devctrl.blog/posts/the-comprehensive-guide-to-typing-cangjie-on-linux-using-fcitx5-and-rime/

**Comment by wengxt** [comment]
https://fcitx5-android.github.io/faq/#_2

此处有多种不同版本的仓颉码表
https://github.com/fcitx/fcitx5-table-extra/tree/master/tables

**Comment by wengxt** [comment]
也可以从更新器或者 f-droid 安装

https://f5a.torus.icu/fdroid/repo/
