### ISSUE TITLE
双拼与百度云拼音 API 的结合问题

### ISSUE THREAD

**Issue by Aloxaf** [fcitx/fcitx5-chinese-addons#2]
## 问题描述
注意到双拼在调用云拼音时传递的字符串是以 `'` 分隔并且展开后的音节

按理来说这样提前划分音节，云拼音的效果应该更好才对，然而事实上百度 api 对于划分了音节的词要求似乎更加严格，常常会出现没有结果的情况，举例如下
```
https://olime.baidu.com/py?rn=0&pn=1&ol=1&py=xin'shu'ru'fa'zhong'dian'gai'shan
```
上面的 URL 返回结果是空

但如果去掉其中的 `'`，则可以成功返回 `新输入法重点改善`
```
https://olime.baidu.com/py?rn=0&pn=1&ol=1&py=xinshurufazhongdiangaishan
```

## 供参考方案

我首先考虑过直接去掉 `'`，但是这样可能会导致返回一些在双拼用户看来莫名其妙的结果
比如以下两个 URL，前者返回 `显然二进制`，后者返回 `西安然而禁止`
```
https://olime.baidu.com/py?rn=0&pn=1&ol=1&input_type=py&py=xianranerjinzhi
https://olime.baidu.com/py?rn=0&pn=1&ol=1&input_type=py&py=xi'an'ran'er'jin'zhi
```
我个人认为这个代价是可以接受的，但是不一定每个人都这么想

所以我想或许可以增加一个选项比如 “云拼音忽略分词” 供那些愿意牺牲一部分准确性换取更强大的云拼音提示的效果的双拼用户。

**Comment by wengxt** [comment]
非要我说就是baidu的api太挫了…我怀疑是不是内部有个长度限制，他们可能在背后硬编码了那个最长的限制以防占用过多服务器资源

如果你觉得ok你可以自己加一个啊，有一个办法就是你把结果里返回的拼音结果和原始拼音验证一下看看切分上能不能批评

**Comment by Aloxaf** [comment]
@wengxt 
确实很挫, Google 的 API 就没这个问题...

分析了一下发现确实有限制, 不过不是长度而是音节数目——最多五个音节
比如 `li'li'li'li'li` 和 `zhuang'zhuang'zhuang'zhuang'zhuang` 都是可以的, 然而 `li'li'li'li'li'li` 就不行.

如果不划分音节似乎没有限制长度, 测试了 `zhuangzhuangzhuangzhuangzhuangzhuangzhuangzhuangzhuangzhuangzhuangzhuangzhuangzhuangzhuang` 都可以.

不知道百度程序员是怎么想的, 划分了音节反而被限制了?
我觉得他们应该是想限制长度, 但是没有考虑客户端传过来的拼音没有划分音节的情况.

我自己先打个 patch 用着算了......

**Comment by wengxt** [comment]
目前暂时没有打算解决百度这边的打算。
新增的 google cn 源可能对国内是个更好的选择。

**Comment by Aloxaf** [comment]
GoogleCN 竟然能用么，好耶

**Comment by Aloxaf** [comment]
GoogleCN 感觉延迟有点点大，看到群里有大佬抓到了微软云拼音的 API：https://cn.bing.com/qsonhs.aspx?FORM=IPXIME&mkt=zh-cn&ds=kunlunadvance&o=&count=30&q=%7B_t_:1,_id_:_00000000000000000000000000000000_,_q_:_pinyinchuan_%7D
自己试了一下感觉还行

想问一下这个加到本项目里有没有风险？
