### ISSUE TITLE
无法在appimage的应用里使用中文输入法

### ISSUE THREAD

**Issue by FlyInWind1** [fcitx/fcitx5-chinese-addons#20]
在appimage应用里，比如我常用的navicat，无法使用fcitx5输入法

**Comment by FlyInWind1** [comment]
好像是因为appimage应用自带的qt没有fctix5插件,但是直接把插件的so文件拷过去似乎没效果.

**Comment by wengxt** [comment]
一般来说，是插件编译时的 Qt 版本不对。一个可能的 workaround 是用 QT_IM_MODULE=ibus 来运行

**Comment by FlyInWind1** [comment]
> 一般来说，是插件编译时的 Qt 版本不对。一个可能的 workaround 是用 QT_IM_MODULE=ibus 来运行

是不是需要另外下什么插件，我在命令行输入 QT_IM_MODULE=ibus 后，再在命令行运行软件，之前正常的普通软件也不能输入了。
archlinux,我已装的软件包
fcitx5 0.0.0.20200626-1
fcitx5-chinese-addons 0.0.0.20200626-1
fcitx5-material-color 0.0.0.20200410-1
fcitx5-pinyin-zhwiki 20200620-1
fcitx5-qt 0.0.0.20200616-1
kcm-fcitx5 0.0.0.20200615-1

**Comment by FlyInWind1** [comment]
QT_IM_MODULE=fcitx 可以，谢谢
