### ISSUE TITLE
关于拼音混合大写字母输入的支持

### ISSUE THREAD

**Issue by Seterplus** [fcitx/fcitx5-chinese-addons#202]
您好，我遇到了与 #194 类似的情况，具体如下：
1. 输入"woquKTVla"时，希望可以得到类似“我去KTV啦”的候选词，即将所有大写字母当成一个专有英语词，不知是否在那个bug中一并被修复了？
2. 在直接输入"KTV"或者"BUS"等纯大写字母时，希望可以做到直接上屏，因为输入大写字母时大概率是希望直接输入对应字符而非输入拼音。目前会按照拼音显示"K T V"或"BU S"对应的中文，中间的空格让人难以看清自己是否输入了正确的英语词语；输入"S3"这样的带数字的词语时还会输入错误。

这篇博文提到了这是一个很多人需要的功能，且提供了一个桌面端的lua workaround：[uppercase.lua](https://github.com/debuggerx01/fcitx5_customizer/blob/master/assets/uppercase_addon/lua/uppercase_dis_ime/uppercase.lua) - https://bbs.deepin.org/post/262182 ，但说实话效果并不完美。在安卓端，似乎没有找到好的解决方案。

感谢！

**Comment by Seterplus** [comment]
对了，fcitx4是原生支持需求2（大写字母直接上屏）的，更新到fcitx5后出现此问题。对于需求1我不是很确定，因为我只在手机端使用这种混合输入的模式 :)

**Comment by Seterplus** [comment]
刚才发现将A-Z的所有大写字母加入“触发快速输入”可以在安卓端完美解决需求2……在手机端可以接受输入后多按一下来选择输入的词语，且还自带快速输入的英语单词补全功能（比如，输入"Andr"时自动提示出"Android"）。
但是在桌面端还是希望少按一次空格选字，所以希望有一个“大写字母直接上屏”的选项，在桌面端开启，在安卓端关闭……

**Comment by wengxt** [comment]
没有这种打算

现在这种行为对于各种情况都相对比较一致。

过去，当你输入大写之后继续输入的小写反而并不能作为一个整体

如果没有可以同时解决两种问题的建议我并不打算修改这个行为
