### ISSUE TITLE
Add option to disable candidate list for table engine

### ISSUE THREAD

**Issue by kuroya2mouse** [fcitx/fcitx5-chinese-addons#205]
### Summary

![изображение](https://github.com/user-attachments/assets/f446ebca-e5f6-462a-9167-45612b801d3c)

i don't need candidate list when using "Translite - Russian (Table)" and i can't found option to disable it

**Comment by wengxt** [comment]
Please give https://github.com/fcitx/fcitx5-chinese-addons/pull/206 a try and let me know if you still some more change.

Basically, if we only hide candidate without any additional change, you probably won't everything you want. So I added some additional behavior change to make it more like m17n.
