### ISSUE TITLE
多音字「无」的组词拼音错误

### ISSUE THREAD

**Issue by oldherl** [fcitx/fcitx5-chinese-addons#22]
![image](https://user-images.githubusercontent.com/172495/85195674-24b1da80-b307-11ea-96b3-0ae1ec96d40d.png)
我想打 磨坏了
这里无显然不读mo

**Comment by lilydjwg** [comment]
https://www.youtube.com/watch?v=eRiqCmJ_ePo

**Comment by oldherl** [comment]
那个「酒」还是尖音呢，显然不是普通话……

**Comment by cathaysia** [comment]
无是一个多音字，百度第一条就是。比如“南无阿弥托福”

**Comment by wengxt** [comment]
首先，这里并没有实际的组词… language model 的部分是没有读音的，只有在词的匹配的时候有读音，所以在计算这句话的时候 无 坏了 几个字正好计算结果上概率最高而已。

open phrase 里面没有给无这个字的不同读音指定概率，那 libime 只能假设是一半对一半

无 20928 mo wu

**Comment by wengxt** [comment]
https://github.com/fcitx/libime/commit/d1357e28b2c0943184d3c654523977c44ef69ec1
