### ISSUE TITLE
五笔无法使用

### ISSUE THREAD

**Issue by a188037445** [fcitx/fcitx5-chinese-addons#23]
我用的是 debian testing 系统和 kde 桌面，今天看到 fcitx5 更新了就想用下试试，我已经安装了 fcitx5、fcitx5-chinese-addons、kde-config-fcitx5，但是只能使用拼音，不能用五笔。

具体问题是，切换到五笔的时候弹出的提示有个括号，里面写的是 不可用，而且我输入后上屏的只有字母。我试过了 五笔字形 和 五笔拼音都是这样的。

我不太了解 fcitx5 的开发进度，想问下现在五笔是不是本来就不可用，还是别的原因。

**Comment by wengxt** [comment]
我觉得是打包问题 @hosiet 他可能更清楚

提示不可用一般来说就是加载数据文件失败了

**Comment by a188037445** [comment]
弄明白了，原因是我禁用了“额外拼音功能‘模块，所以五笔用不了了，启用这个模块之后就没问题了。

请问五笔一定要依赖这个模块吗？如果不是必须的话，请修复下。

**Comment by wengxt** [comment]
本来就是在同一个包里的，没必要特地支持成可选。

**Comment by a188037445** [comment]
但是这样用户很容易踩到坑...

**Comment by zhuatw** [comment]
真是大坑, 而且这个网页很难 搜索到,  当时, 以为是 fcitx5, 换成 fcitx4, 了, 用了一会又不行了, 可能相依赖太强了,

**Comment by wengxt** [comment]
@zhuatw 如果你用的是debian/ubuntu那是debian打包的bug，依赖关系写的不对。我已经通知他们修了

**Comment by hosiet** [comment]
如果你是 debian/ubuntu 用户且正在使用 `fcitx5-table` 提供的五笔功能：请检查是否同时安装了 `fcitx5-module-pinyinhelper` 和 `fcitx5-module-punctuation` 。在这两个包也装好并重启系统后，理论上五笔就不会再出现“不可用”的提示。

这个问题我已经在 fcitx5-chinese-addons/5.0.9-2 以及更新版本中已经修复。如果你的 fcitx5-chinese-addons 的版本不够高，那么需要按照上一段提供的做法手动装好两个依赖包；如果版本够高了，那么这个问题应该不再出现。

**Comment by wengxt** [comment]
如果你关心的是用户意外禁用的问题的话。现在 configtool 会在禁用的时候对影响的其他附加组件进行警告提示。

![图片](https://user-images.githubusercontent.com/259684/147181454-6248e236-86fb-4fdc-97aa-0ad93b4f325d.png)
