### ISSUE TITLE
有没有制作码表的方法或工具？

### ISSUE THREAD

**Issue by tankb52** [fcitx/fcitx5-chinese-addons#24]
我是用 98五笔的，目前的码表里面没有98五笔方案。
我搜了一下，好像 fcitx5 上的码表变成了 main.dict 格式，但是没找到如何制作的办法。
不过 github 上已经有人制作了两笔码表，这是怎么做的呢？
码表工具还没有开放吗？

**Comment by wengxt** [comment]
libime_tabledict 

文本格式和 fcitx 4 是一样的
