### ISSUE TITLE
[Feature Repuest] 拼音输入法设置单行模式

### ISSUE THREAD

**Issue by hosxy** [fcitx/fcitx5-chinese-addons#3]
这是五笔输入法：
![2019-11-03_17-04](https://user-images.githubusercontent.com/17108640/68082823-70893f80-fe5c-11e9-828f-dffd29a2bd53.png)
这是拼音输入法
![2019-11-03_17-05](https://user-images.githubusercontent.com/17108640/68082824-71ba6c80-fe5c-11e9-8159-555263876879.png)

请问拼音输入法如何设置能达到和五笔输入法这样，候选框只有一行，键入字符在预编辑区？
如果没有的话，能否为拼音输入法中也加入五笔这种单行模式(inline_preedit ?)

Windows10 和 OSX 自带的输入法都是图一的显示效果。感觉既然fcitx5的五笔输入法能做到，拼音应该也能做到。

**Comment by wengxt** [comment]
这个主要是有那么几个其他的原因所以一直没有做
在程序失去焦点的时候，预输入的文本有些程序只能提交，有些可以修改，为了保持行为一致所以都是让实际相关的文字显示为预输入。

如果变成单行那就只能把拼音显示在预输入里面（类似iOS），这样有时候会提交一些不怎么合理的内容例如被插入了空格的拼音（iOS上也确实是如此…觉得非常奇怪）。

**Comment by OliverLew** [comment]
跟进个问题。看到楼主的repo里提及使用XIM的应用无法开启Preedit。这个是fcitx这边无法改变的吗？ @wengxt

**Comment by wengxt** [comment]
xim有几个模式，需要在xim server启动时决定，over the spot 可以输入框跟随光标
on the spot可以程序内preedit但不能跟随光标。（你问我为什么这么设计，我也不知道，而且libx11也不打算改……）

所以为了最正常的使用默认就是over the spot。

**Comment by OliverLew** [comment]
谢谢解答。好像找到你提的这个wontfix了：
https://bugs.freedesktop.org/show_bug.cgi?id=1580
这种老issue好像很少有人再注意了，好可惜啊
