### ISSUE TITLE
[Feature Repuest] 能不能让数字小键盘保持英文状态

### ISSUE THREAD

**Issue by hosxy** [fcitx/fcitx5-chinese-addons#4]
能否加个设置让数字小键盘永远保持英文状态，fcitx4好像就是这样(很多win下的输入法貌似也是这样)，有时候打中文的时候需要打英文的 `.`号，这样就不用切换输入法了。

**Comment by wengxt** [comment]
Fixed in pinyin / table. No extra option needed.
