### ISSUE TITLE
五笔输入法的一级简码有点问题

### ISSUE THREAD

**Issue by a188037445** [fcitx/fcitx5-chinese-addons#41]
我发现有好几个键敲出来不是一级简码，比如 A（工）、V（发）、L（国） 等等，是不支持一级简码吗？

**Comment by wengxt** [comment]
我这好像没问题，你改了什么配置吗？
可以把用户数据发过来看看

~/.local/share/fcitx5/table/wbx.user.dict 和 ~/.local/share/fcitx5/table/wbx.history

**Comment by a188037445** [comment]
这俩文件我都没改，不过名字是 wubi 不是 wbx

好像没法上传，这两个文件都是二进制文件...

一级简码打出来好像会自动调整频率，会不会是因为这个？如果是的话，可以把一级简码固定下来，不让它自动调整。

**Comment by a188037445** [comment]
压缩了下，可以上传了。

[table.tar.gz](https://github.com/fcitx/fcitx5-chinese-addons/files/5252844/table.tar.gz)

**Comment by wengxt** [comment]
一直就有针对一级简码二级简码的功能，现在我在意的是哪里导致它出了问题

**Comment by a188037445** [comment]
> 一直就有针对一级简码二级简码的功能，现在我在意的是哪里导致它出了问题

我测试了下 A 键，确实会自动调整，原来不在第一个候选的，多选几次就跑到第一个了。

**Comment by wengxt** [comment]
建议先更新到最新，然后展示一下你的配置里面的选项情况

**Comment by wengxt** [comment]
包括所有相关的包（提示五笔名字改了你可能需要重新添加一次）

关键是这个选项，如果是2但是还有问题的话请再回复
<img width="300" alt="图片" src="https://user-images.githubusercontent.com/259684/93955807-7488af00-fd05-11ea-89e2-c7e5ad028045.png">

**Comment by a188037445** [comment]
是我的问题，我把这个选项改成 0 了，因为之前发现有单字不常用但是排在前面，现在改成大于 0 就好了...

**Comment by a188037445** [comment]
问题解决
