### ISSUE TITLE
简拼出错；自定义双拼应该在哪修改？另外需要固顶词。

### ISSUE THREAD

**Issue by jangbeyond** [fcitx/fcitx5-chinese-addons#44]
1. 不管是全拼还是双拼都无法正确使用简拼。「eq」 输出的是「恶且」而不是「而且」，「oe」输出的是「哦恶」而不是「偶尔」，诸如此类，只要是零声母的字都会出问题。
2. 双拼设置里有一个「自定义」，但是找不到配置文件的位置。
3. 另外是不是应该考虑加一个固顶词，或者自定义短语的功能？（感觉把码表输入法和拼音结合一下应该就可以了。）

**Comment by wengxt** [comment]
1、我觉得双拼不应该能用这种类型的简拼。全拼应该支持一下
2、 ~/.local/share/fcitx5/pinyin/sp.dat
3、建议考虑 quickphrase 之类的功能

**Comment by jangbeyond** [comment]
> 
> 
> 1、我觉得双拼不应该能用这种类型的简拼。全拼应该支持一下
> 2、 ~/.local/share/fcitx5/pinyin/sp.dat
> 3、建议考虑 quickphrase 之类的功能

双拼可需要简拼了。。。除了自然码这种零声母使用引导键的，还有小鹤这样不使用引导键的方案啊。

**Comment by wengxt** [comment]
> > 1、我觉得双拼不应该能用这种类型的简拼。全拼应该支持一下
> > 2、 ~/.local/share/fcitx5/pinyin/sp.dat
> > 3、建议考虑 quickphrase 之类的功能
> 
> 双拼可需要简拼了。。。除了自然码这种零声母使用引导键的，还有小鹤这样不使用引导键的方案啊。
> 
> @wengxt

反正也是支持的，没啥问题，我是指你输入比如 ee 的时候就不应该匹配 er 了

**Comment by VWWVVW** [comment]
方便说一下自定义双拼的设置具体格式是怎样的吗，网上逛了一圈没有找到

**Comment by wengxt** [comment]
@VWWVVW https://github.com/fcitx/libime/blob/f21f48b01dc6b84c10e009b876c39e768b21905d/test/testshuangpinprofile.cpp#L110 参考这个测试，有两个例子

**Comment by VWWVVW** [comment]
是这样吗，我直接复制的例子：
~/.local/share/fcitx5/pinyin/sp.dat 文件內容：
```
[方案]
方案名称=自定义

[零声母标识]
=O*

[声母]
# 双拼编码就是它本身的声母不必列出
ch=I
sh=U
zh=V

[韵母]
# 双拼编码就是它本身的韵母不必列出
ai=L
an=J
ang=H
ao=K
ei=Z
en=F
eng=G
er=R
ia=W
ian=M
iang=D
iao=C
ie=X
in=N
ing=Y
iong=S
iu=Q
ong=S
ou=B
ua=W
uai=Y
uan=R
uang=D
ue=T
ui=V
un=P
ve=T
uo=O
```
但是好像没被正确识别
例如我想打 **测试**（_ceui_）会被识别成 **测ui**（_ce'u'i_）

**Comment by wengxt** [comment]
@VWWVVW ~/.config/fcitx5/pinyin/sp.dat

**Comment by VWWVVW** [comment]
@wengxt  可以了，谢谢 xd
