### ISSUE TITLE
有没有像fcitx一样输入https://等字符串之后自动跳转到英文输入的配置？

### ISSUE THREAD

**Issue by 1900011604** [fcitx/fcitx5-chinese-addons#49]
这样打Latex和Markdown的时候就不用频繁切换输入法了。

**Comment by wengxt** [comment]
目前没有

**Comment by wengxt** [comment]
给拼音加上了这个功能 https://github.com/fcitx/fcitx5-chinese-addons/commit/7ef04af1aaf3a35153fcbb79b050fdcd4cc559c3

**Comment by 1900011604** [comment]
请问自定义的设置文件在哪里找呢？

**Comment by wengxt** [comment]
？配置工具找拼音配置就行了

**Comment by 1900011604** [comment]
![Screenshot_20201117_092729](https://user-images.githubusercontent.com/65082432/99328484-23d1a480-28b7-11eb-902d-85aee439021d.png)

没找到呢
版本号是这样的：（不知道有没有最新）

![Screenshot_20201117_092911](https://user-images.githubusercontent.com/65082432/99328592-60050500-28b7-11eb-8a50-4cb09f0d532a.png)

**Comment by wengxt** [comment]
你得重启一下 fcitx，拉到底

**Comment by 1900011604** [comment]
看到了，谢谢！话说可以把“trigger to quick phrase”改成直接切换到英文输入吗？而且这个好像对$$,\[\],```这样的符号无效？

**Comment by wengxt** [comment]
和符号无关，目前只是实现假定一定有字母部分。

**Comment by wengxt** [comment]
可以用单个字符的字符串了。
