### ISSUE TITLE
特殊符号

### ISSUE THREAD

**Issue by 1900011604** [fcitx/fcitx5-chinese-addons#50]
特殊符号

导入rime-dict项目中[symbols.dict.yaml](https://github.com/yangshann/rime-dict)词库即可在拼音中输入希腊字母、部分数学符号及Emoji表情

示例:

希腊字母:输入alpha即可输出α

数学符号:输入jifen即可输出∫

特殊符号:输入cha可输出✕,✖

序号:输入qi可输出Ⅶ,⑦

Emoji表情:输入haha可输出😃,😆 

这些在不用繁体字的时候也能用吗？能用的话如何导入？或者以后考虑默认导入，像微软拼音一样在第五个位置显示？

**Comment by wengxt** [comment]
Fcitx 自己的 emoji ：https://github.com/fcitx/fcitx5-chinese-addons/blob/master/im/pinyin/emoji.txt
这和繁体字没关系吧。

你想导入什么的话就参考上面的格式然后配置工具里用文本格式导入（需要合法拼音，所以例如 alpha 不行）

其他你可以用 lua 来扩展，现有你可以参考 https://github.com/fcitx/fcitx5-chinese-addons/blob/master/im/pinyin/pinyin.lua
（分号的快速输入之后输入 fh 可以看后续提示）
