### ISSUE TITLE
自动选择功能建议 

### ISSUE THREAD

**Issue by yueduz** [fcitx/fcitx5-chinese-addons#51]
![2020-11-25 16-17-22 的屏幕截图](https://user-images.githubusercontent.com/1448159/100200770-0bf2c400-2f3a-11eb-8853-3de519b30104.png)
能不能设置为一个正则,编码符合正则自动选择 .

另外翻译为"超过此码长无重码自动选择" 更好理解.

**Comment by wengxt** [comment]
请具体举例说明一下你确实想用的正则

**Comment by yueduz** [comment]
> 请具体举例说明一下你确实想用的正则

- /u./
- /v./
上面两个是我想使用的正则。但是顶功输入法会需要更复杂的正则。如果加入这个功能,顶功类输入法也能完美支持。

如果按原设计，只要超过设定码长，无重码都会被自动选择。

**Comment by wengxt** [comment]
建议再具体描述一下你的正则和逻辑之间的关系
例如，你的两个正则都只能精确匹配两个字符的情况，你输入 u 的时候你预期发生什么呢？
输入 u 开头的两个字符你预期发生什么呢？
输入 u 开头的三个字符你预期发生什么呢？

我在网络上查了一下超强音型，v u 看起来是功能性的码，但是也都有1,2,3不同的长度

目前我看起来你说的逻辑和具体要进行的实现不一致

**Comment by yueduz** [comment]
我那个正则写错了,应该是:
- /^u./
- /^v./

u或v开头的编码只有两码,官方的输入方案中,u或v开头的编码是没有重码的.
下面是二笔码表部分:
![2020-11-26 17-55-33 的屏幕截图](https://user-images.githubusercontent.com/1448159/100336048-a4f40e80-3010-11eb-8cd3-270c3e4f7d32.png)
输入"uc"后自动选择"重",不用空格,也不用满四码自动选择.在一楼画红线的功能中需要无重码才能自动选择,有重码就不行了.


rime中有这种设置,但是rime不能实现自动选择但不上屏.
![2020-11-26 17-52-54 的屏幕截图](https://user-images.githubusercontent.com/1448159/100335774-50e92a00-3010-11eb-8e73-d0fcbba7a2ce.png)

**Comment by wengxt** [comment]
听起来你有两种正则希望使用，分别对应两种目前 fcitx 支持的自动选择的选项，当然，大部分情况这两种正则应当设置为同一个
1、当目前输入编码匹配正则时，且无重码时，进行自动选择
2、当目前输入编码匹配正则并且输入了一个新码时，进行自动选择

**Comment by yueduz** [comment]
> 听起来你有两种正则希望使用，分别对应两种目前 fcitx 支持的自动选择的选项，当然，大部分情况这两种正则应当设置为同一个
> 1、当目前输入编码匹配正则时，且无重码时，进行自动选择
> 2、当目前输入编码匹配正则并且输入了一个新码时，进行自动选择

完美
