### ISSUE TITLE
一次删除一组编码

### ISSUE THREAD

**Issue by yueduz** [fcitx/fcitx5-chinese-addons#52]
在快速打字时,特别是不使用自动提交,一次输入一句时,发现错误时并不知道是哪一个编码输错了,所以,能不能一次删除一组编码重新开始输入.

**Comment by wengxt** [comment]
可以考虑加一个 ctrl + delete 用来删除整组

**Comment by wengxt** [comment]
增加了用 ctrl + delete(拼音)/backspace 删除整个码的功能
