### ISSUE TITLE
托盘图标右键点击一次后无法再点第二次.

### ISSUE THREAD

**Issue by yueduz** [fcitx/fcitx5-chinese-addons#53]
fcitx5:    5.0.2
gnome: 3.38.1

在gnome中,重启一次fcitx5服务,能右键点一次挺盘打开配置程序,点第二次无反应.
![2020-11-25 16-43-44 的屏幕截图](https://user-images.githubusercontent.com/1448159/100203331-6c373500-2f3d-11eb-8d68-5a45ed71fe6f.png)

**Comment by wengxt** [comment]
我试了几个不同的插件都没有问题

**Comment by wengxt** [comment]
以下是我测试过的
https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
https://extensions.gnome.org/extension/615/appindicator-support/
不知道你用的是哪个

**Comment by yueduz** [comment]
我使用这个<https://extensions.gnome.org/extension/1031/topicons/>
这个我也试了<https://extensions.gnome.org/extension/2890/tray-icons-reloaded/>
情况都一样.
我再次试了,在xorg下会弹不出来,在Wayland下没有问题.
