### ISSUE TITLE
Failed to compile fcitx5-chinese-addons on Ubuntu 20.04.

### ISSUE THREAD

**Issue by hongyi-zhao** [fcitx/fcitx5-chinese-addons#54]
On Ubuntu 20.04, I try to compile fcitx5-chinese-addons but failed. The detailed steps and error messages are shown below:

```
$ git clone https://github.com/fcitx/fcitx5-chinese-addons.git fcitx5-chinese-addons.git 
$ cd fcitx5-chinese-addons.git 
$ mkdir build && cd $_
$ cmake ..
CMake Warning at CMakeLists.txt:13 (find_package):
  By not providing "FindFcitx5ModuleLuaAddonLoader.cmake" in
  CMAKE_MODULE_PATH this project has asked CMake to find a package
  configuration file provided by "Fcitx5ModuleLuaAddonLoader", but CMake did
  not find one.

  Could not find a package configuration file provided by
  "Fcitx5ModuleLuaAddonLoader" with any of the following names:

    Fcitx5ModuleLuaAddonLoaderConfig.cmake
    fcitx5moduleluaaddonloader-config.cmake

  Add the installation prefix of "Fcitx5ModuleLuaAddonLoader" to
  CMAKE_PREFIX_PATH or set "Fcitx5ModuleLuaAddonLoader_DIR" to a directory
  containing one of the above files.  If "Fcitx5ModuleLuaAddonLoader"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.61") found components: iostreams 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.61")  
CMake Error at CMakeLists.txt:60 (find_package):
  Could not find a configuration file for package "LibIMETable" that is
  compatible with requested version "1.0.2".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/LibIMETable/LibIMETableConfig.cmake, version: 0.0.1
    /lib/x86_64-linux-gnu/cmake/LibIMETable/LibIMETableConfig.cmake, version: 0.0.1



-- Configuring incomplete, errors occurred!
See also "/home/werner/Public/repo/github.com/fcitx/fcitx5-chinese-addons.git/build/CMakeFiles/CMakeOutput.log".
See also "/home/werner/Public/repo/github.com/fcitx/fcitx5-chinese-addons.git/build/CMakeFiles/CMakeError.log".
```

I still can't figure out the missing packages/dependencies based on the error log shown above. Any hints will be highly appreciated.

Regards,
HY

**Comment by karuboniru** [comment]
- Compile and install `fcitx5-lua`, which is needed to build `fcitx5-chinese-addons`
- Compile and install a latest version (to name it, `1.0.2`) of `libime`, older version is not accepted by latest `fcitx5-chinese-addons`, while you could checkout a older commit that will build with `v0.0.1`.

**Comment by wengxt** [comment]
you need update your package. BTW flatpak.fcitx-im.org/ might be easier to use.

**Comment by hongyi-zhao** [comment]
>     * Compile and install `fcitx5-lua`, which is needed to build `fcitx5-chinese-addons`

Got it. Thanks a lot for your note.

> 
>     * Compile and install a latest version (to name it, `1.0.2`) of `libime`, older version is not accepted by latest `fcitx5-chinese-addons`, while you could checkout a older commit that will build with `v0.0.1`.

Got it. I  add some notes here for those who want to compile it by themselves. The `libime` package needs another packages named as `kenlm` which is just an empty placeholder folder in the `libime` repo, so the working compiling steps are as following:

```
git clone https://github.com/fcitx/libime.git libime.git
git clone https://github.com/kpu/kenlm.git kpu/kenlm.git

rm -fr libime.git/src/libime/core/kenlm
cp -r kpu/kenlm.git libime.git/src/libime/core/kenlm
cd libime.git
mkdie build && cd $_
cmake ..
env all_proxy=http://127.0.0.1:8080 make -j44
sudo make install
```

**Comment by wengxt** [comment]
You’d better check how git sub modules work...

hongyi-zhao <notifications@github.com>于2020年12月6日 周日07:03写道：

**Comment by hongyi-zhao** [comment]
Thanks a lot. I omitted the needed package are maintained as a submodule. Therefore, the steps should look like the following:

```
git clone https://github.com/fcitx/libime.git libime.git
cd libime.git
git submodule update --init --recursive
[...]
```

**Comment by LAP47** [comment]
I'm having this same problem on Debian 12.  So how do I fix it?
