### ISSUE TITLE
 无法删除历史输入 & 关于候选的问题 & 关于小键盘回车的问题（补充）

### ISSUE THREAD

**Issue by suica-me** [fcitx/fcitx5-chinese-addons#55]
Linux arch 5.9.14-arch1-1-vfio #1 SMP PREEMPT Sat, 26 Dec 2020 16:03:13 +0000 x86_64 GNU/Linux
![image](https://user-images.githubusercontent.com/16483753/103278863-d5fca000-4a0f-11eb-9a2a-1e6556ebae23.png)
无法删除历史输入：
使用pinyin的时候无法删除历史记录，具体如下
![image](https://user-images.githubusercontent.com/16483753/103278723-8a49f680-4a0f-11eb-89bb-44c5563a6f92.png)
![image](https://user-images.githubusercontent.com/16483753/103278757-97ff7c00-4a0f-11eb-817d-63f76ac12bfe.png)
ctrl+7之后调出forget界面之后点击并不能删除，下次输入同样组合的时候仍然是这个词在第一位
PS：我甚至没有主动输入过此单词

关于候选的问题
是否可能在输入ng的时候给出“那个” “哪个”这样的候选而不是以下的
![image](https://user-images.githubusercontent.com/16483753/103279304-d5183e00-4a10-11eb-8c40-a9533b9cc4e3.png)

**Comment by suica-me** [comment]
补充
关于小键盘（数字键盘）的问题（想了一下似乎不应该提到fcitx5那边）
在输入的时候按回车可以直接输入当前输入的字母， 但是按小键盘回车()的时候并不行，会变成 换行/发送。应该是keycode不一样不过并未找到可以修改的地方。
非常感谢

**Comment by wengxt** [comment]
那是根据基础概率算出来的，不是由于你输入过。如何删除也不会影响。你就输入你想要输入的就是了。多输入几次自然就调整了。

**Comment by wengxt** [comment]
其他的都分别解决了

**Comment by suica-me** [comment]
非常感谢，辛苦了
