### ISSUE TITLE
fcitx5pinyin输入法用户词库无法保存

### ISSUE THREAD

**Issue by zzy-ac** [fcitx/fcitx5-chinese-addons#56]
fcitx5pinyin输入法用户词库貌似无法保存

**Comment by wengxt** [comment]
请具体描述一下为什么你会这么认为

另外

 libime_pinyindict -d ~/.local/share/fcitx5/pinyin/user.dict -

libime_history ~/.local/share/fcitx5/pinyin/user.history -

可以用来导出你输入的历史，建议先检查是否有你输入的内容

**Comment by zzy-ac** [comment]
多谢，是我误会了，我发现还是有词库的，不过确实有时候会不灵，我之前提问是因为我上次开机一个之前反复输入的词语在我没有删除缓存和配置文件的情况下无法直接出词语了，然后过来一会儿它又可以正常使用了。感谢您的回复、希望越做越好。

**Comment by wengxt** [comment]
如果你上次关机不太正常（例如强制重启）可能没有保存吧，下个新版本增加了一个空闲时定时保存的功能
