### ISSUE TITLE
繁體中文下的cangjie3 輸出簡體字

### ISSUE THREAD

**Issue by leesei** [fcitx/fcitx5-chinese-addons#57]
我是用Arch Linux 的[fcitx5-chinese-addons](https://archlinux.org/packages/community/x86_64/fcitx5-chinese-addons/) 包
而同是繁體中文下的cangjie5 就會輸出繁體字，但字碼改了我不熟 :laughing:

![Screenshot](https://user-images.githubusercontent.com/544400/104094667-41c2f080-52cd-11eb-9508-7fb6ceed388b.png)

**Comment by wengxt** [comment]
我查看了一下原始数据，应该是繁体啊？

fcitx 里面好几个仓颉

<img width="393" alt="图片" src="https://user-images.githubusercontent.com/259684/104112295-d283d700-52a1-11eb-83fa-91e14af61f24.png">

你是不是选择的不对？

例如 bcbcc 输出的偏旁都是“貝” 而不是“贝”

**Comment by wengxt** [comment]
另一个可能是你是不是开启了简繁转换？快捷键默认是 ctrl shift f

**Comment by leesei** [comment]
我也看了 https://github.com/fcitx/fcitx5-table-extra/blob/master/tables/cangjie3.txt
確實owjr 是繁體"個"

確實是简繁转换呢, 謝謝

我怎樣檢查是否啟用了简繁转换? fcitx4 好像是在選單有顯示狀態的
我實測過這功能是對應每個輸入法獨立的?

**Comment by wengxt** [comment]
托盘图标右键有展示状态

这个功能在 fcitx 5 确实是对每个输入法独立的。按下 ctrl shift f 默认会有桌面提示你切换了
