### ISSUE TITLE
fcitx5 / Chinese does not work, fcitx5 crashes

### ISSUE THREAD

**Issue by JENKOP** [fcitx/fcitx5-chinese-addons#59]
I can't get fcitx5 to work for chinese/pinying. 
When I try to switch it crashes on Bodhi Linux, a Ubuntu 20.04 derived linux.
When started from shell, this is the last line before the crash:
I2021-01-23 01:49:01.766814 kimpanel.cpp:121] Kimpanel new owner

When it crashes:

2021-01-23 02:05:32.739358 addonmanager.cpp:177] Loaded addon fullwidth
2021-01-23 02:05:32.740433 addonmanager.cpp:177] Loaded addon chttrans
2021-01-23 02:05:34.602353 addonmanager.cpp:177] Loaded addon cloudpinyin

=========================

Fcitx 5.0.4 -- Get Signal No.: 11
Date: try "date -d @1611363934" if you are using GNU date ***
ProcessID: 16137
fcitx5(+0xe5ef)[0x564fde4785ef]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f6fddefa210]
/lib/x86_64-linux-gnu/libFcitx5Core.so.7(_ZNK5fcitx10InputPanel13candidateListEv+0x29)[0x7f6fde47dff9]
/usr/lib/x86_64-linux-gnu/fcitx5/pinyin.so(+0x1a7e6)[0x7f6fd72c57e6]
/lib/x86_64-linux-gnu/libFcitx5Core.so.7(_ZN5fcitx8Instance9postEventERNS_5EventE+0x3c4)[0x7f6fde41c834]
/lib/x86_64-linux-gnu/libFcitx5Core.so.7(_ZN5fcitx12InputContext8keyEventERNS_8KeyEventE+0x156)[0x7f6fde44d516]
/usr/lib/x86_64-linux-gnu/fcitx5/dbusfrontend.so(+0x11f8a)[0x7f6fdc2e1f8a]
/usr/lib/x86_64-linux-gnu/fcitx5/dbusfrontend.so(+0x121c2)[0x7f6fdc2e21c2]
/lib/x86_64-linux-gnu/libFcitx5Utils.so.2(+0x507e7)[0x7f6fde3347e7]
/lib/x86_64-linux-gnu/libFcitx5Utils.so.2(+0x41380)[0x7f6fde325380]
/lib/x86_64-linux-gnu/libsystemd.so.0(+0x70c4b)[0x7f6fdddffc4b]
/lib/x86_64-linux-gnu/libsystemd.so.0(+0x5809e)[0x7f6fddde709e]
/lib/x86_64-linux-gnu/libsystemd.so.0(+0x58537)[0x7f6fddde7537]
/lib/x86_64-linux-gnu/libsystemd.so.0(+0x3f6a7)[0x7f6fdddce6a7]
/lib/x86_64-linux-gnu/libsystemd.so.0(sd_event_dispatch+0x111)[0x7f6fdddcf141]
/lib/x86_64-linux-gnu/libsystemd.so.0(sd_event_run+0x98)[0x7f6fdddd2b78]
/lib/x86_64-linux-gnu/libsystemd.so.0(sd_event_loop+0x5f)[0x7f6fdddd2d9f]
/lib/x86_64-linux-gnu/libFcitx5Utils.so.2(_ZN5fcitx9EventLoop4execEv+0x15)[0x7f6fde327195]
/lib/x86_64-linux-gnu/libFcitx5Core.so.7(_ZN5fcitx8Instance4execEv+0x54)[0x7f6fde426304]
fcitx5(+0xd166)[0x564fde477166]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f6fddedb0b3]
fcitx5(+0xd94e)[0x564fde47794e]

Any idea?

**Comment by wengxt** [comment]
This might be a real bug or a installation issue, but AFAIK ubuntu 20.04 doesn't have such new fcitx 5 available, did you compile it yourself?

If so, could you try to compile it with debug symbol by passing -DCMAKE_BUILD_TYPE=Debug ?

Then you can do things like:
start a xterm (it is important to use xterm because you don't want a terminal that uses input method)
run (disable xim so xterm won't have input method thus it won't freeze upon fcitx crash)
```
gdb --args fcitx5 --disable xim 
```

After it crashes, type bt to display the backtrace.

**Comment by JENKOP** [comment]
Thank you for your fast reply. No, I did not compile it myself:
$ sudo add-apt-repository ppa:ikuya-fruitsbasket/fcitx5
$ sudo apt install fcitx5-mozc
$ im-config -n fcitx

I always used fcitx before but since I started to use Ubuntu 20.04 it starts, it works, but does not produce chinese output. Same problem on two computers.

**Comment by wengxt** [comment]
But here's problem, I checked the PPA, and it doesn't seem to have chinese-addons but only mozc? So I guess you mixed both packages from ppa and packages from offical repo.

<img width="713" alt="图片" src="https://user-images.githubusercontent.com/259684/105606320-7dd66680-5d4d-11eb-859d-75cd9f5cba39.png">


Right now the fcitx5 packages in offical repo is very old (Pre 5.0.0), which means it contains binary incompatible changes. Then it won't be surprise if it have weird crash.

If you want to try latest fcitx 5 on 20.04, I suggest you to use fcitx5 from flatpak with fcitx 4's im module on your host.
Mozc + ChineseAddons should be available on flatpak by now. I haven't yet pushed all things to flathub, but you could also try fcitx's private repo flatpak.fcitx-im.org.

If you can read Chinese I have a blog post about it:
https://www.csslayer.info/wordpress/fcitx-dev/fcitx5-on-flatpak/

**Comment by JENKOP** [comment]
SInce I updated to Ubuntu 20.04 many many important things don't work anymore.
I can't even write chinese now.
Can you give an English explanation? The I tried to follow the Chinese Version, now I get an error. I don't even know how to run the app. 
flatpak run org.fcitx.Fcitx5 ?

Neither do I like nor understand the change to flatpak and snap.

**Comment by wengxt** [comment]
I currently don't have a 20.04 system but a 20.10 one, I hope there's not too much difference there:

If you want to ensure from a clean setup, you can do this first:
```
# list existing remotes you configured
flatpak remote-list
# remove the remote, this will also remove package you installed from remote so it will be clean
flatpak remote-delete name_of_remote
# remote list should print nothing afterwards.
flatpak remote-list
```

```
# Remove fcitx5 package from host
sudo apt-get purge 'fcitx5*' 'libfcitx5*'
# You still need im module on the host, this will install all the fcitx4 one but don't worry this works with fcitx5.
sudo apt-get install fcitx-frontend-all
# Add flathub
flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo
# Flathub now provides some fcitx package, so you don't really need the fcitx5-unstable one.
flatpak install --user flathub org.fcitx.Fcitx5
flatpak install --user flathub org.fcitx.Fcitx5.Addon.Mozc
flatpak install --user flathub org.fcitx.Fcitx5.Addon.ChineseAddons

# Select YES, and select none, so im-config won't start an input method for you.
im-config
```

You need to add fcitx5 from flatpak to autostart, e.g. with gnome, open gnome-tweaks and add it under Startup applications.
Then you also need to do some manual config that usually done by im-config before:
Open ~/.profile , then add following lines to the end:
```
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
```

Re-login and hopefully it will work now. (You may check it by using "Ctrl + ;" to see if it gives you a clipboard popup from fcitx )

Then from the tray icon you should be able to use "Configure" to add input methods.
