### ISSUE TITLE
我创建了一个新世纪五笔码表的项目，可以让 fcitx5 用户使用新世纪五笔输入法

### ISSUE THREAD

**Issue by beavailable** [fcitx/fcitx5-chinese-addons#63]
项目地址：https://github.com/beavailable/better-wubi

基本上一键安装就可以用了，有需要的可以来看看。

**Comment by wengxt** [comment]
…这个，你发个邮件给 fcitx@googlegroups.com 可能比加个 issue 在这好能让更多人看见…

大部分新五笔不能直接包括在内的主要原因主要是版权/专利……

不过刚刚一查确实过期了……至少没有专利问题，只有版权问题了。

**Comment by beavailable** [comment]
没关系，我只是想在这留个记录，以后别人就可以在 issues 里查到了。

**Comment by wengxt** [comment]
最好来说还是可以合并一个，既然汉字的编码方案专利过期了，只是词库可以试试用fcitx自己的wubi86生成一个

**Comment by beavailable** [comment]
好像是可以，写个脚本把86的码表对照新世纪的码表修改下就行了，只是不知道这样算侵权吗？
如果不算的话，我考虑写一个。虽然86的词库很一般，但是只要能用就行了。

顺便问下，专利在哪可以查到呢？我搜索了下没找到，在专利局网站也不知道搜什么关键字。
