### ISSUE TITLE
能不能不要把常见的多音字中不常见的那个读音的优先级放那么高啊？

### ISSUE THREAD

**Issue by 1900011604** [fcitx/fcitx5-chinese-addons#65]
比如：
![1612158493](https://user-images.githubusercontent.com/65082432/114893729-9469f680-9e40-11eb-83e0-cf77213d6763.jpg)
每次打jie会先出这个字而不是我想要的“解”
她的也比解得优先级高

**Comment by wengxt** [comment]
更新 libime 到最新版

**Comment by wengxt** [comment]
指 1.0.6

**Comment by 1900011604** [comment]
还有一个类似的bug是打`gonge`的时候第一个出来的是“**弥**”

`libime version: libime-git-1.0.7.r1.gf6193fa-1`

**Comment by wengxt** [comment]
那个主要还是有个拆字的功能，弓尔

**Comment by wengxt** [comment]
你可以在配置里禁用
