### ISSUE TITLE
[Feature Quest] rq(日期) 和 sj(时间) 候选

### ISSUE THREAD

**Issue by cathaysia** [fcitx/fcitx5-chinese-addons#66]
在很多输入法中键入 rq/sj 可以显示当前日期或时间，fcitx5 似乎没有这个功能，请问可以给予考虑吗？

**Comment by xingwozhonghua** [comment]
https://www.csslayer.info/wordpress/fcitx-dev/fcitx-5-%e7%9a%84%e6%8b%bc%e9%9f%b3%e6%9c%89%e5%93%aa%e4%ba%9b%e6%96%b0%e5%8a%9f%e8%83%bd/

时间功能，已通过fcitx5-lua模块实现。

**Comment by cathaysia** [comment]
感谢帮助 :)

**Comment by CyrusYip** [comment]
在 Arch 的话，安装 `fcitx5-lua` 包再重启 Fcitx 5 就行了。
