### ISSUE TITLE
考虑对内置 ccedit 词库的支持？

### ISSUE THREAD

**Issue by cathaysia** [fcitx/fcitx5-chinese-addons#67]
我从 [ccedit](https://www.mdbg.net/chinese/dictionary?page=cc-cedict) 中导出了一个词库：https://github.com/cathaysia/fcitx5_dicts/releases/tag/0.0.1

一共 10,564，目前看来质量很不错，毕竟是从辞典中导出的，而且体积也不大，也许它可以被内嵌到软件包中？

**Comment by cathaysia** [comment]
呃，看起来词库好像还是太大了 :(
也许我应该做个 2k 高频词的

**Comment by liangqi** [comment]
试试 https://github.com/liangqi/chinese-frequency-word-list ？

**Comment by cathaysia** [comment]
> 试试 https://github.com/liangqi/chinese-frequency-word-list ？

我已经添加了对 chinese-frequency-word-list 的支持

但是我在想是不是需要单独为词典做一个 ci 仓库。通过打包的形式将字典分为多个包。这样就能和 fcitx5 分开。用户安装不安装就看他自己了

但是现在词典的质量来源比较少，而且有些质量很难得到保证

**Comment by cathaysia** [comment]
chinese-frequency-word-list 这个做出来只有 2.55KB 。而且有 56064 行，我觉得确实不错
