### ISSUE TITLE
能否支持带音调拼音(键盘输入拼音，得到带音调拼音，而不是汉字)

### ISSUE THREAD

**Issue by liangqi** [fcitx/fcitx5-chinese-addons#70]
实例1
键盘输入：women
输出文本：wǒmen 或者 wǒ men

实例2
键盘输入：zhongguoren
输出文本：zhōngguó rén 或者 zhōng guó rén

实例3
键盘输入：womendoushizhongguoren
输出文本：wǒmen dōu shì zhōngguó rén

现状，通过自定义xkb文件，估计也可以得到带符号的拼音字符，但估计很复杂。
fcitx-m17n中好像支持类似的方式[参考][1]，“Example: nv1=nǖ nv2=nǘ nv3=nǚ nv4=nǜ Shei2 xiang3 he1 ka1fei1? = Shéi xiǎng hē kāfēi?”

近期需求，按单字输出带音调的拼音，或者按词典中的分词输出相应的带音调的拼音。
远期需求，根据标点符号情况，句首字母大写。

[1]: https://www.reddit.com/r/ChineseLanguage/comments/8knamc/pinyin_tone_marks_debianxfcefcitx/

**Comment by wengxt** [comment]
就用 m17n 啊？https://github.com/fcitx/fcitx5-m17n 里面有输入拼音的。搜一下拼音就有了
chinese-addons 的数据里面本来也没有音调

**Comment by liangqi** [comment]
不想输入1234的音调呀，而且基于词和句的智能输入方式显然更强大呀

**Comment by wengxt** [comment]
问题是，即使做，但是那个数据本身也是无音调的，从何来做？
多音字本身的问题也解决不了

没必要为了这个引入更复杂的，你去找 rime 定制一个说不定都更简单
