### ISSUE TITLE
声母简拼功能支持

### ISSUE THREAD

**Issue by tkkcc** [fcitx/fcitx5-chinese-addons#74]
搜狗拼音输入法有声母简拼功能：在输入大于等于4个字符时，将每个键入看作声母，如果历史或字典中存在就作为候选第二或第三项。这样输入短语很方便，只需要敲声母，并且基本不影响原先的体验。希望fcitx5能加入这个功能。
![image](https://user-images.githubusercontent.com/17373509/123553023-a4407800-d7ab-11eb-9656-d2497db8125b.png)
![image](https://user-images.githubusercontent.com/17373509/123553195-58da9980-d7ac-11eb-955f-bf435289f698.png)
![image](https://user-images.githubusercontent.com/17373509/123553115-05684b80-d7ac-11eb-8262-f848a70ef9eb.png)

**Comment by wengxt** [comment]
短语已经有了按前四个字匹配的功能了。

https://github.com/fcitx/libime/commit/e9eceb9d271cdad829c61d534f95a9bc8b11d93d

你说的主要是双拼相关的问题吧，不太确定双拼用户会不会想用这种

**Comment by tkkcc** [comment]
这个功能全拼也有，搜狗叫首字母简拼。fcitx5现在的短语匹配功能需要键入的字符更多，不管是全拼还是双拼。
![image](https://user-images.githubusercontent.com/17373509/123573938-800f8600-d801-11eb-953f-95c467a8b4c7.png)
![image](https://user-images.githubusercontent.com/17373509/123573804-30c95580-d801-11eb-80d4-5e7de6decb9d.png)

**Comment by tkkcc** [comment]
确实是双拼相关，这个需求也曾有用户提过。
https://forum.ubuntu.org.cn/viewtopic.php?t=457612
> 举例来说，我输入 hdvx 就出来 活动中心，输入 vhrmghg 就出来 中华人民共和国
搜狗输入法的双拼模式是支持的。
linux 的 fcitx-pinyin, fcitx-sunpinyin,fcitx-rime 的双拼模式都不支持。
fcitx-table-cn-ziran 是支持的，但是词库太弱了。

https://www.zhihu.com/question/27040623/answer/325592611
> 不行哎，我想找一个这样的软件，比如中华人民共和国自然码双拼需要输入 vshwrfmngshego ，我希望可以输入 vhrmghg 就可以完成。

fcitx5可以将最短长度作为选项，0为不启用，和matchLongWord功能一样。

这个功能在搜狗、微软的双拼中也都支持，搜狗老版通过“超级简拼”开启，新版已无法关闭。
![image](https://user-images.githubusercontent.com/17373509/123582955-56f6f180-d811-11eb-9063-20c7f138582c.png)
![image](https://user-images.githubusercontent.com/17373509/123582982-65450d80-d811-11eb-8820-e677f0c83776.png)
![image](https://user-images.githubusercontent.com/17373509/123583019-7aba3780-d811-11eb-930f-1f9173c8857d.png)

![image](https://user-images.githubusercontent.com/17373509/123582281-206ca700-d810-11eb-9a87-684fbb39be45.png)

**Comment by tkkcc** [comment]
感谢，有效！
