### ISSUE TITLE
[Proposal] read dict and table files using `StandardPath`

### ISSUE THREAD

**Issue by rocka** [fcitx/fcitx5-chinese-addons#75]
Currently, `sc.dict` and table input method's table is located by libime's compile-time definition `LIBIME_INSTALL_PKGDATADIR`

https://github.com/fcitx/fcitx5-chinese-addons/blob/c22be0122ea0002ab81500227ff3ebc6ac17afb8/im/table/engine.cpp#L146-L148

https://github.com/fcitx/fcitx5-chinese-addons/blob/c22be0122ea0002ab81500227ff3ebc6ac17afb8/im/pinyin/pinyin.cpp#L609-L611

https://github.com/fcitx/fcitx5-chinese-addons/blob/c22be0122ea0002ab81500227ff3ebc6ac17afb8/im/table/wbx.conf.in.in#L9-L10

In the mean time, pinyin user history is located by `StandardPath`

https://github.com/fcitx/fcitx5-chinese-addons/blob/c22be0122ea0002ab81500227ff3ebc6ac17afb8/im/pinyin/pinyin.cpp#L616-L617

Typically, `LIBIME_INSTALL_PKGDATADIR` is defined as `/usr/share/libime`, which can be found by

```cpp
standardPath.openSystem(StandardPath::Type::Data, "libime/sc.dict", O_RDONLY);
```

If that's not the desired path, it can be overrided by env `XDG_DATA_DIRS`.

As for `sc.dict` path, I have a working patch: https://github.com/rocka/fcitx5-chinese-addons/commit/bc7dd3e0f69e6cadc4ab5c7beacffe452bb228ef , to locate them using `StandardPath`. But there would be more changes for table input methods to adopt this: change `File=` in input method conf file to relative path, change dict loading code, etc.

---

PS: I came up with this when patching dict path for Android: https://github.com/rocka/fcitx5-chinese-addons/commit/5007d80a6e53e061fe47951b4c23f9fbd4d3eab1 . If those changes could be made, Android would be able to use upstream chinese addons without additional patching (actually not, because of #71). And if it's not feasible, feel free to close it.

**Comment by wengxt** [comment]
It's not guarantee that the data follow xdg. I'd suggest you can have a environment variable to override this.

You can try to do something like this:
https://github.com/fcitx/libime/blob/b9d91f1f0277577373ca61121012a0c947976f0d/src/libime/core/languagemodel.cpp#L257
