### ISSUE TITLE
在 Chrome Beta 里，所有 input 框输入，待选栏的删除键会影响 input 框内内容

### ISSUE THREAD

**Issue by ety001** [fcitx/fcitx5-chinese-addons#77]
我是 Manjaro KDE 用户，使用 Chrome Beta 版本 92.0.4515.80。

在输入的时候，如果 input 框（包括浏览器地址栏）内已有内容，继续输入的过程中，某个拼音输入错误，想要删除的时候，敲击退格键会同样影响当前聚焦的 input 框内容。比如目前 input 框内容是“我们”，接着输入“喜欢”，敲击拼音 “xihuai“，发现 n 输入成了 i，这时敲击一次退格键，结果 input 框内变为 “我”，待选区域内容为“xihua”。

在 Firefox 和其他文本编辑器中测试，没有类似问题。

补充：又安装了 Chrome 正式版，发现正式版没有问题。

**Comment by wzl20001001** [comment]
> 我是 Manjaro KDE 用户，使用 Chrome Beta 版本 92.0.4515.80。
> 
> 在输入的时候，如果 input 框（包括浏览器地址栏）内已有内容，继续输入的过程中，某个拼音输入错误，想要删除的时候，敲击退格键会同样影响当前聚焦的 input 框内容。比如目前 input 框内容是“我们”，接着输入“喜欢”，敲击拼音 “xihuai“，发现 n 输入成了 i，这时敲击一次退格键，结果 input 框内变为 “我”，待选区域内容为“xihua”。
> 
> 在 Firefox 和其他文本编辑器中测试，没有类似问题。
> 
> 补充：又安装了 Chrome 正式版，发现正式版没有问题。

安裝 fcitx-gtk 包就可以了。

**Comment by xingwozhonghua** [comment]
https://github.com/fcitx/fcitx5/issues/311

chrome的bug已经报了。

https://bugs.chromium.org/p/chromium/issues/detail?id=1232283

**Comment by zyf0330** [comment]
正式版现在也有相同的问题 92.0.4515.107 
@wzl20001001 fcitx-gtk 是哪个包 没找到，我是 ubuntu

**Comment by wzl20001001** [comment]
> @wzl20001001 fcitx-gtk 是哪个包 没找到，我是 ubuntu

Ubnutu 上名字应该是 `fcitx5-frontend-gtk3` 和 `fcitx5-frontend-gtk3`，但是要注意这是fcitx5的，目前的国内商业输入法大部分不支持，可以试试小狼毫。

**Comment by wengxt** [comment]
fixed in latest chromium
