### ISSUE TITLE
希望能添加98版五笔输入法

### ISSUE THREAD

**Issue by homtoo** [fcitx/fcitx5-chinese-addons#78]

**Comment by lilydjwg** [comment]
我倒是有个很久以前做的 fcitx4 的98版五笔码表： https://lab.lilydjwg.me/share/wb98.mb
你可以转一转用。或者你自己找个98的码表转了用。

**Comment by homtoo** [comment]
谢谢你的及时回复。不情之请是希望能将五笔98包含在fcitx5-chinese-addons里，这样才能开箱即用。窃以为开箱即用才是对用户友好的。

**Comment by wengxt** [comment]
主要是版权/专利等问题，不知道现在能不能用有没有过期

**Comment by homtoo** [comment]
五笔98的版权/专利已过期。

**Comment by wengxt** [comment]
那现在主要就是需要一个许可证合适的数据了

**Comment by homtoo** [comment]
https://wb98.gitee.io/
有志愿者整理了五笔98资源，声明开源，并且长期维护。

**Comment by yanhuacuo** [comment]
> 主要是版权/专利等问题，不知道现在能不能用有没有过期

98方案现在已无版权，非常感谢囧神考虑收录 『98五笔方案』，我是98五笔资源库的维护者之一，目前所有平台上的 98五笔方案实现都是我们在沟通联络。

『98五笔资源库』：[https://wb98.gitee.io/](https://wb98.gitee.io/)
『98五笔主页』：[http://www.98wubi.com/](http://www.98wubi.com/)

我们的 github 主档：(https://github.com/yanhuacuo/98wubi-tables)

[这里](https://github.com/yanhuacuo/fcitx5-issues/blob/main/fcitx5-table.tar.gz)是我们正在尝试的 fcitx5 原生码表方式的实现，不过遇到了一些 [问题](https://github.com/fcitx/fcitx5/issues/376)

**Comment by wengxt** [comment]
@yanhuacuo 既然你的问题已经解决了，你可以提交一个 pull request 一个给 fcitx5-table-extra
