### ISSUE TITLE
在开启预测 "prediction" 功能后，如何输入空格

### ISSUE THREAD

**Issue by allenryb** [fcitx/fcitx5-chinese-addons#79]
非常感谢开发者！我第一次接触 fcitx5，虽然 google 了一圈，但仍未找到答案。
如果提问太简单，请见谅！

我在开启 "prediction" 功能后，由于空格键被用作选词键，导致无法输入空格。
同样的问题也发生在输入数字上。

例如，在如下情况下，如何**直接输入空格或者数字**？
![image](https://user-images.githubusercontent.com/6965371/131839254-9ae24508-d881-4138-938b-d4ba4d5c267e.png)

另外，我想请问，是否可以**自定义取消 fcitx5 输入框的快捷键**？
当前的 "ESC" 可以取消输入，但是
一方面，"ESC" 离常用字母键区太远，不容易按到，
另一方面，"ESC" 键有时会做更多，比如在如下 github 中写 issue，按 "ESC" 键会直接退出整个输入状态
所以想做仅仅只退出 fcitx5 输入框的自定义，不知如何实现？

**Comment by wengxt** [comment]
Esc 预测模式这个处理是个小 bug，不应该传递给客户端的

**Comment by wengxt** [comment]
我不可能给所有的按键都弄成可以自定义的，esc 觉得太远的话，不如尝试 xkb 设置成 caps lock 变成 esc 的方式。

**Comment by wengxt** [comment]
另外你说的有道理，预测的话空格应该弄成不选词，数字键还是保留选词直到 esc
