### ISSUE TITLE
Traditional Pinyin with Dvorak layout?

### ISSUE THREAD

**Issue by dheera** [fcitx/fcitx5-chinese-addons#87]
Is there any way to get this combination?
Traditional Chinese
Pinyin input
Dvorak keyboard

I had it on fcitx4 but fcitx5 seems to be a regression and doesn't provide this. I don't see Traditional Pinyin and even the Simplified Pinyin switches to QWERTY when I switch to it.

Pinyin should never change the layout of the keyboard -- there are lots of non-QWERTY users in the world including AZERTY, QWERTZ, Colemak, etc. and the beauty of Pinyin is that it is not tied to a layout like Bopomofo is.

Thanks!

**Comment by wengxt** [comment]
That certainly should work, can you share the output of fcitx5-diagnsoe?

**Comment by wengxt** [comment]
![图片](https://user-images.githubusercontent.com/259684/146861060-7567ff97-b377-461d-9a81-af9c78db101e.png)

An example setup to use dvorak ^

As traditional Chinese pinyin, use rime or use pinyin + Ctrl+Shift+F to enable conversion.
