### ISSUE TITLE
部分字符乱码

### ISSUE THREAD

**Issue by Corona09** [fcitx/fcitx5-chinese-addons#88]
中文拼音输入法下, 有部分字符始终乱码, 如图, 候选框中的第4条

![](https://raw.githubusercontent.com/Corona09/anime-img-bed/main/Screenshot_2021-12-24_00%3A23%3A19.png)

![](https://raw.githubusercontent.com/Corona09/anime-img-bed/main/Screenshot_2021-12-24_01%3A16%3A20.png)

经过我的尝试, 可以判断不是emoji: 我从[这里](https://github.com/fcitx/fcitx5-chinese-addons/blob/master/im/pinyin/emoji.txt)找到了16个带"niu"这个音的emoji, 都能正常显示.

个人猜测乱码字符可能是一些生僻字

**Comment by wengxt** [comment]
生僻字不能叫「乱码」，你没有字体那是那是字体覆盖不够全的问题
![图片](https://user-images.githubusercontent.com/259684/147273296-6cbdc51b-6c9b-4732-b6cb-6b5c9687706a.png)
