### ISSUE TITLE
建议返回的候选词根据字数由大到小排列。

### ISSUE THREAD

**Issue by xyl23333** [fcitx/fcitx5-chinese-addons#96]
在无法干预词库顺序的情况下，匹配字数越多的往往越接近正确词。

一些字数更多的词被排列在字数少的词之后，这些可能跟以词库顺序排序有关，建议将所有返回的候选词先进行字数从大到小排序，同字数下进行词频、匹配度等其他排序。

例如：以原神的细胞词库为例，输入keqing之后，“刻晴”被排在很多单字词之后。

![Screenshot_20220419-233429.png](https://user-images.githubusercontent.com/46397979/164044618-1dd5726e-9898-488f-bcd6-6da0bf7ca3ae.png)
![Screenshot_20220419-232948.png](https://user-images.githubusercontent.com/46397979/164044661-4932070a-069a-4acc-9ac1-25a13ebf1f41.png)

**Comment by wengxt** [comment]
@xyl23333 匹配的长度已经是一个考虑的因素了，会有不同的权重，细胞词库的问题是这些都是默认unknown没有输入过，这部分的评分权重较低
