### ISSUE TITLE
建议限制联想组词的行为

### ISSUE THREAD

**Issue by JaHIY** [fcitx/fcitx5-chinese-addons#97]
我从 [rime-emoji](https://github.com/rime/rime-emoji) 项目里转换了一个emoji词库，导入了fcitx里，然后发现，我连续几次用hao来输入🙂之后，我打hao ren，fcitx就把第一个候选词变成了🙂人了，能不能限制这种奇怪的联想行为？

我自己转换出来的词库： [emoji dict files for fcitx pinyin](https://gist.github.com/JaHIY/7006251d5a668b6054dd714f0acbc580)

现在的输入法情况：
![Fcitx5_for_Android设置](https://user-images.githubusercontent.com/733107/164666385-aad13ab2-e7d8-491e-aebf-582e135426ac.png)
![Fcitx5_for_Android输入过程](https://user-images.githubusercontent.com/733107/164670308-0bf98ec4-9a13-47a9-9da4-4d738a0c92c3.png)

**Comment by wengxt** [comment]
不能。代码行为很符合预期。

**Comment by wengxt** [comment]
建议，你把词库里的单字对应修改一下，或者在词库里分配一个额外的低分给单字拼音给emoji。

输入法知道的只有拼音和字的对应关系，并不在意它来自什么词库，或者是什么内容

**Comment by JaHIY** [comment]
@wengxt 行吧，还有一个问题，导入的自定义词典第三列，究竟是个什么系数？

**Comment by wengxt** [comment]
对数概率的调整值，越大越靠前

**Comment by wengxt** [comment]
不要设置很大的，具体多少你可以尝试，如果正数的话可以尝试小于1 的正数

**Comment by JaHIY** [comment]
@wengxt 好的，3Q
