### ISSUE TITLE
小数字键盘的数字之后的标点仍是全角的

### ISSUE THREAD

**Issue by yutent** [fcitx/fcitx5-chinese-addons#98]
**Describe the bug**
发现了fcitx5的一个小bug,  就是设置"字母或数字之后输入半角标点"这个功能,  在主键盘上没问题,  但是在小数字键盘那里按就不生效了(输入法大概是判断小数字键盘的数字不是数字了 。; )

**To Reproduce**
![image](https://user-images.githubusercontent.com/11972650/165656970-49047236-ec7e-46d1-b06b-c003c68aeb2e.png)

**Desktop (please complete the following information):**
 - Desktop: Cinnamon 5.2
 - Display server type: X11
 - OS: LMDE 5

**Comment by wengxt** [comment]
已修复，不过既然你已经用小键盘输入数字了，姑且说一下，小键盘的小数点是不会经过标点转换的，你可以直接用小键盘的小数点来输入

**Comment by yutent** [comment]
> 已修复，不过既然你已经用小键盘输入数字了，姑且说一下，小键盘的小数点是不会经过标点转换的，你可以直接用小键盘的小数点来输入

我就是使用 小数字键盘上的小数点来输入的,  它会变成 句号。  

### ---------------------------------------------------------

另外, 发现了一个新bug

主键盘上 输入 "字母或数字"之后, 再按 `.`,  它是会正常变成`小数点`了,  然后, 此时按一下 `回退键(BackSpace)`, 这个小数点, 会被删除, 然后又恢复成句号。

**Comment by CoelacanthusHex** [comment]
@yutent 这是 feature
