### ISSUE TITLE
预测中出现的词汇无法使用空格键上屏

### ISSUE THREAD

**Issue by chenshijie-uos** [fcitx/fcitx5-chinese-addons#99]
预测中出现的词汇无法使用空格键上屏

**Comment by chenshijie-uos** [comment]
![Record_select-area_20220510170202](https://user-images.githubusercontent.com/69958796/167591574-1cd66133-796d-41c5-a1a7-abf07ac1d926.gif)

**Comment by rocka** [comment]
设计上就是这样的吧，不然预测候选词出现之后，除非按 Esc 清空候选框，否则没法输入空格

**Comment by wengxt** [comment]
如上面所说，设计就是这样
